---
# generic settings
main_username: "{{ secret_fuzzy_name }}"
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# grog.package
package_list:
  - name: curl
  - name: fail2ban
  - name: git
  - name: htop
  - name: lm-sensors
  - name: net-tools
  - name: sudo
  - name: wget

# telegraf_force_install: false
# telegraf_ver: 1.18.1
telegraf_influx_url: 'http://192.168.30.14:8086'
telegraf_influx_org: Cosmere
syncthing_user: "{{main_username}}"

# autorestic_ver: v1.1.2
autorestic_generator_output_path: "/home/{{main_username}}"
# restic_ver: v0.12.1
# runitor_ver: v0.8.0
runitor_url: "{{secret_hc_ping_url}}"

# geerlingguy.ntp
ntp_timezone: America/New_York

# geerlingguy.docker
docker_users:
  - "{{ main_username }}"

# ironicbadger.docker_compose_generator
appdata_path: /home/{{main_username}}/docker
global_env_vars:
  - "UID={{ main_uid }}"
  - "GID={{ main_gid }}"
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: /home/{{ main_username }}
