---
# generic settings
main_username: "{{ secret_fuzzy_name }}"
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# grog.package
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: lm-sensors
  - name: net-tools
  - name: ncdu
  - name: sudo
  - name: wget

# geerlingguy.docker
docker_packages_state: latest

# bash aliases
bash_aliases:
  - alias: c
    command: clear
  - alias: e
    command: exit

bash_autorestic_aliases:
  - alias: arsnapshot
    command: autorestic exec -av -- snapshots
  - alias: arbackup
    command: autorestic backup -a
  - alias: arprune
    command: autorestic forget -a -- prune

bash_apt_aliases:
  - alias: agi
    command: sudo apt install $c
  - alias: agr
    command: sudo apt remove $c
  - alias: agu
    command: sudo apt update && sudo apt upgrade

bash_git_aliases:
  - alias: ga
    command: git add --all
  - alias: gp
    command: git push $c
  - alias: gpdry
    command: git push --dry-run
  - alias: gpf
    command: git push --force
  - alias: gb
    command: git branch
  - alias: gbd
    command: git branch -d $c
  - alias: gcam
    command: git commit -am $c
  - alias: gcm
    command: git commit -m $c
  - alias: gcheck
    command: git checkout
  - alias: gm
    command: git merge $c
  - alias: gms
    command: git merge --squash $c
  - alias: gst
    command: git status
  - alias: gpl
    command: git pull
  - alias: glast
    command: git log -1 HEAD --stat
  - alias: greset
    command: git reset HEAD~1

bash_systemctl_aliases:
  - alias: sc-start
    command: sudo systemctl start $c
  - alias: sc-stop
    command: sudo systemctl stop $c
  - alias: sc-restart
    command: sudo systemctl restart $c
  - alias: sc-enable
    command: sudo systemctl enable $c
  - alias: sc-disable
    command: sudo systemctl disable $c
  - alias: sc-status
    command: sudo systemctl status $c
  - alias: sc-reload
    command: sudo systemctl daemon-reload

bash_docker_aliases:
  - alias: dc-up
    command: docker compose up -d $c
  - alias: dc-down
    command: docker compose down $c
  - alias: dc-pull
    command: docker compose pull $c
  - alias: dc-exec
    command: docker compose exec $c
  - alias: dc-ps
    command: docker compose ps
  - alias: dc-start
    command: docker compose start $c
  - alias: dc-stop
    command: docker compose stop $c
  - alias: dc-restart
    command: docker compose restart $c
  - alias: dc-rm
    command: docker compose rm $c

bash_pacman_aliases:
  - alias: pacup
    command: sudo pacman -Syu
  - alias: pacin
    command: sudo pacman -S
  - alias: pacloc
    command: sudo pacman -Qi
  - alias: pacmir
    command: sudo pacman -Syy
  - alias: pacrem
    command: sudo pacman -Rns

bash_yay_aliases:
  - alias: yaup
    command: yay -Syu
  - alias: yain
    command: yay -S
  - alias: yaloc
    command: yay -Qi
  - alias: yamir
    command: yay -Syy
  - alias: yarem
    command: yay -Rns

bash_dnf_aliases:
  - alias: dnfs
    command: dnf search
  - alias: dnfu
    command: sudo dnf upgrade
  - alias: dnfi
    command: sudo dnf install
  - alias: dnfr
    command: sudo dnf remove
  - alias: dnfc
    command: sudo dnf clean all

# autorestic_ver: 1.1.2
autorestic_config_user: "{{ main_username }}"
# restic_ver: 0.12.1
# runitor_ver: 0.8.0
runitor_url: "{{ secret_hc_ping_url }}"

### Github API
github_api_user: fuzzymistborn
github_api_pass: "{{ secret_github_api_pass }}"
github_api_auth: yes

# geerlingguy.ntp
ntp_timezone: America/New_York

# geerlingguy.docker
docker_users:
  - "{{ main_username }}"

### Docker-Compose with docker-compose-generator
appdata_path: /home/{{ main_username }}/docker
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: /home/{{ main_username }}
docker_compose_hostname: "{{ hostname }}"
