---
# generic settings
main_username: "{{ secret_fuzzy_name }}"
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# grog.package
package_list:
  - name: curl
  - name: fail2ban
  - name: git
  - name: htop
  - name: lm-sensors
  - name: net-tools
  - name: sudo
  - name: wget

telegraf_ver: 1.17.3
autorestic_ver: 1.0.3

# geerlingguy.ntp
ntp_timezone: America/New_York

# geerlingguy.docker
docker_users:
  - "{{ main_username }}"

# ironicbadger.docker_compose_generator
appdata_path: /home/{{main_username}}/docker
global_env_vars:
  - "UID={{ main_uid }}"
  - "GID={{ main_gid }}"
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
docker_compose_generator_uid: "{{ main_uid }}"
docker_compose_generator_gid: "{{ main_gid }}"
docker_compose_generator_output_path: /home/{{ main_username }}
