---
target_os: ubuntu
hostname: ambition

### Install packages with grog.package
package_list:
  - name: curl
  - name: iperf3
  - name: restic
  - name: net-tools
  - name: python3
  - name: wget
  - name: wireguard

### Bash Aliases
bash_docker: true
bash_autorestic: true
bash_systemctl: true
bash_apt: true

pull_backup: true
# hugo_ver: 0.88.1
# lego_ver: 4.4.0

### Cronjobs
cronjobs:
  - name: Backup
    job: /usr/local/bin/runitor -uuid {{ secret_hc_ambition_db_backup }} -- /home/{{ main_username }}/scripts/db_backup.sh
    user: "{{ main_username }}"
    minute: 0
    hour: 5
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_prune_ambition }} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 0
    hour: 6
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_check_ambition }} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 45
    hour: 5
    day: 1
  - name: Cert Update
    job: /usr/local/bin/runitor -uuid {{ secret_hc_ambition_certs }} -- /home/{{ main_username }}/scripts/certs.sh
    user: root
    minute: 0
    hour: 19
    day: 1,15
  - name: Data Backup
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_backup_ambition }} -- /usr/local/bin/autorestic backup -a -c /home/{{ main_username }}/.autorestic.yml
    user: root
    minute: 15
    hour: 5

### UFW Rules
ufw:
  - comment: 'ssh'
    rule: 'allow'
    port: '22'
    proto: 'any'
    route: 'no'
  - comment: 'reverse proxy'
    rule: 'allow'
    port: '80'
    proto: 'tcp'
    route: 'no'
  - comment: 'reverse proxy'
    rule: 'allow'
    port: '443'
    proto: 'tcp'
    route: 'no'
  - comment: 'iperf'
    rule: 'allow'
    port: '5201'
    proto: 'tcp'
    route: 'no'
  - comment: 'wireguard tunnel'
    rule: 'allow'
    port: '51282'
    proto: 'udp'
    route: 'no'
  - comment: 'gitea'
    rule: 'allow'
    port: '222'
    proto: 'tcp'
    route: 'no'
  - comment: 'portainer'
    rule: 'allow'
    port: '9001'
    proto: 'tcp'
    route: 'no'
  - comment: 'tailscale adapter'
    rule: 'allow'
    interface: tailscale0
    direction: in
    proto: 'any'
    route: 'no'

### Caddy Config
caddy_systemd_capabilities_enabled: true
caddy_systemd_network_dependency: false
caddy_packages:  ["github.com/hslatman/caddy-crowdsec-bouncer"]
caddy_conf_dir: /home/{{ main_username }}/caddy
caddy_config: "{{ lookup('template', 'roles/ambition/templates/Caddyfile.j2') }}"

### Autorestic Config
autorestic_config_user: "{{ main_username}}"
autorestic_user_directory: /home/"{{ main_username}}"
autorestic_run_check: false
autorestic_config_yaml:
  version: 2
  backends:
    b2_docker:
      type: b2
      path: "{{ secret_restic_b2_bucket }}:/linode/docker"
      key: "{{ secret_restic_repo_password }}"
      env:
        - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
        - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"
    b2_db:
      type: b2
      path: "{{ secret_restic_b2_bucket }}:/linode/db"
      key: "{{ secret_restic_repo_password }}"
      env:
        - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
        - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"
    b2_certs:
      type: b2
      path: "{{ secret_restic_b2_bucket }}:/linode/certs"
      key: "{{ secret_restic_repo_password }}"
      env:
        - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
        - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"
  locations:
    docker:
      from: '/home/{{ main_username }}/docker'
      to:
        - b2_docker
      options:
        backup:
          exclude:
            - '/home/{{ main_username }}/docker/umami'
            - '/home/{{ main_username }}/docker/gitea/mariadb'
        forget:
          keep-daily: 1
          keep-weekly: 6
          keep-monthly: 3
    db:
      from: '/home/{{ main_username }}/db_backups'
      to:
        - b2_db
      options:
        forget:
          keep-daily: 1
          keep-weekly: 6
          keep-monthly: 3
    certs:
      from: '/home/{{ main_username }}/lego'
      to:
        - b2_certs
      options:
        forget:
          keep-daily: 1
          keep-weekly: 4

### Docker-Compose with ironicbadger.docker_compose_generator
appdata_path: "/home/{{ main_username }}/docker"
compose_schema_version: '2.1'
containers:
  ###
  - service_name: diun
    container_name: diun
    active: true
    image: crazymax/diun:4.28.0
    restart: always
    volumes:
      - "{{ appdata_path }}/diun/data:/data"
      - "{{ appdata_path }}/diun/config.yml:/diun.yml:ro"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      - LOG_JSON=false
    hostname: "{{ hostname }}"
    include_global_env_vars: true
  ###
  - service_name: uptime
    container_name: uptime
    active: true
    image: louislam/uptime-kuma:1.23.13
    restart: always
    ports:
      - 127.0.0.1:3001:3001
    volumes:
      - "{{ appdata_path }}/uptime:/app/data"
    include_global_env_vars: false
  ###
  - service_name: umami
    container_name: umami
    active: true
    image: ghcr.io/umami-software/umami:mysql-v2.13.1
    restart: always
    ports:
      - 127.0.0.1:3500:3000
    labels:
      - "diun.enable=true"
      - "diun.regopt=ghcr.io"
    environment:
      - DATABASE_URL={{ secret_umami_db_url }}
      - DATABASE_TYPE=mysql
      - HASH_SALT={{ secret_umami_hash }}
    depends_on:
      - umami-db
    include_global_env_vars: false
  ###
  - service_name: umami-db
    container_name: umami-db
    active: true
    image: mariadb:11.5
    restart: always
    volumes:
      - "{{ appdata_path }}/umami/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD={{ secret_db_root_pass }}
      - MYSQL_USER=umami
      - MYSQL_PASSWORD={{ secret_umami_db_pass }}
      - MYSQL_DATABASE=umami
    mem_limit: 200M
    include_global_env_vars: false
  ###
  - service_name: gitea
    container_name: gitea
    active: true
    image: gitea/gitea:1.22.1
    restart: always
    ports:
      - "127.0.0.1:3030:3000"
      - "222:222"
    volumes:
      - "{{ appdata_path }}/gitea/data:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=gitea-db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD={{ secret_gitea_db_pass }}
    include_global_env_vars: false
    depends_on:
      - gitea-db
  ###
  - service_name: gitea-db
    container_name: gitea-db
    active: true
    image: mariadb:11.5
    restart: always
    volumes:
      - "{{ appdata_path }}/gitea/mariadb:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD={{ secret_db_root_pass }}
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD={{ secret_gitea_db_pass }}
      - MYSQL_DATABASE=gitea
    mem_limit: 200M
    include_global_env_vars: false
  ###
  - service_name: woodpecker-github
    container_name: woodpecker-github
    active: true
    image: woodpeckerci/woodpecker-server:v2.7.0
    restart: unless-stopped
    ports:
      - 127.0.0.1:4000:8000
      - 127.0.0.1:9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - "{{ appdata_path }}/woodpecker-github:/data"
    environment:
      - WOODPECKER_GITHUB=true
      - WOODPECKER_GITHUB_CLIENT={{ secret_investiture_github_id }}
      - WOODPECKER_GITHUB_SECRET={{ secret_investiture_github_secret }}
      - WOODPECKER_HOST=https://github.ci.fuzzymistborn.com
      - WOODPECKER_AGENT_SECRET={{ secret_investiture_rpc }}
      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/data/woodpecker.sqlite
      - WOODPECKER_ADMIN=FuzzyMistborn
      - WOODPECKER_GRPC_ADDR=:9000
    include_global_env_vars: false
  ###
  - service_name: woodpecker-gitea
    container_name: woodpecker-gitea
    active: true
    image: woodpeckerci/woodpecker-server:v2.7.0
    restart: unless-stopped
    ports:
      - 127.0.0.1:4001:8000
      - 127.0.0.1:9002:9002
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - "{{ appdata_path }}/woodpecker-gitea:/data"
    environment:
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=https://git.fuzzymistborn.com
      - WOODPECKER_GITEA_CLIENT={{ secret_investiture_gitea_id }}
      - WOODPECKER_GITEA_SECRET={{ secret_investiture_gitea_secret }}
      - WOODPECKER_HOST=https://gitea.ci.fuzzymistborn.com
      - WOODPECKER_AGENT_SECRET={{ secret_investiture_rpc }}
      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/data/woodpecker.sqlite
      - WOODPECKER_ADMIN=FuzzyMistborn
      - WOODPECKER_GRPC_ADDR=:9002
    include_global_env_vars: false
  ###
  - service_name: ntfy
    container_name: ntfy
    image: binwiederhier/ntfy:v2.11.0
    active: true
    command:
      - serve
    environment:
      - TZ={{ ntp_timezone }}
      - NTFY_BASE_URL=http://ntfy.{{ secret_personal_url }}
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/cache/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
    user: 1000:1000
    volumes:
      - "{{ appdata_path }}/ntfy/cache:/var/cache/ntfy"
    ports:
      - 127.0.0.1:4600:80
    restart: unless-stopped
    include_global_env_vars: false
  ###
  - service_name: opengist
    container_name: opengist
    active: true
    image: ghcr.io/thomiceli/opengist:1.7
    restart: unless-stopped
    ports:
      - 127.0.0.1:6157:6157
    volumes:
      - "{{ appdata_path }}/opengist:/opengist"
    include_global_env_vars: false
  ###
  - service_name: pairdrop
    container_name: pairdrop
    active: true
    image: lscr.io/linuxserver/pairdrop:1.10.10
    restart: unless-stopped
    ports:
      - 127.0.0.1:3200:3000
    volumes:
      - "{{ appdata_path }}/pairdrop:/opt/pairdrop"
    environment:
      - RATE_LIMIT=false
      - WS_FALLBACK=true
      - RTC_CONFIG=/opt/pairdrop/rtc.json
    include_global_env_vars: true
  ###
  - service_name: healthchecks
    container_name: healthchecks
    active: true
    image: ghcr.io/linuxserver/healthchecks:3.6.20240904
    restart: always
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - "{{ appdata_path }}/healthchecks/config:/config"
    environment:
      - SITE_ROOT=https://hc.fuzzymistborn.com
      - SITE_NAME=Cosmere Health Checks
      - DEFAULT_FROM_EMAIL=do_not_reply@fuzzymistborn.com
      - EMAIL_HOST={{ secret_snapraid_smtp_host }}
      - EMAIL_PORT=587
      - EMAIL_HOST_USER={{ secret_snapraid_email_address }}
      - EMAIL_HOST_PASSWORD={{ secret_snapraid_email_pass }}
      - EMAIL_USE_TLS=True
      - SUPERUSER_EMAIL={{ secret_email }}
      - SUPERUSER_PASSWORD={{ secret_healtchecks_pass }}
      - REGENERATE_SETTINGS=True
      - REGISTRATION_OPEN=False
      - SECRET_KEY={{ secret_healthchecks_key }}
      - TELEGRAM_BOT_NAME=Cosmere HealthChecks
      - TELEGRAM_TOKEN={{ secret_healthchecks_tg_token }}
      - DOCKER_MODS=linuxserver/mods:healthchecks-apprise
    include_global_env_vars: true
  ###
  - service_name: crowdsec
    container_name: crowdsec
    active: true
    image: crowdsecurity/crowdsec:v1.6.2
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ appdata_path }}/crowdsec/data/:/etc/crowdsec"
      - /home/{{ main_username }}/caddy/:/var/log/caddy
      - "{{ appdata_path }}/gitea/data/gitea/log:/var/log/gitea:ro"
      - /var/log/auth.log:/var/log/ssh/auth.log:ro
      - "{{ appdata_path }}/crowdsec/db:/var/lib/crowdsec/data/"
    environment:
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/http-cve crowdsecurity/whitelist-good-actors LePresidente/gitea timokoessler/uptime-kuma crowdsecurity/sshd
      - BOUNCER_KEY_CADDY={{secret_crowdsec_api}}
      - GID=1000
      - USE_WAL=true
      - TZ={{ ntp_timezone }}
    include_global_env_vars: false
  ###
  - service_name: portainer_agent
    container_name: portainer_agent
    active: true
    image: portainer/agent:2.20.3
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_SECRET={{ secret_portainer_key }}
    include_global_env_vars: false
