---
target_os: ubuntu
hostname: ambition

### Install packages with grog.package
package_list:
  - name: curl
  - name: iperf3
  - name: restic
  - name: net-tools
  - name: python3
  - name: wget
  - name: wireguard

### Bash Aliases
bash_docker: true
bash_autorestic: true
bash_systemctl: true
bash_apt: true

pull_backup: true
# hugo_ver: 0.88.1
# lego_ver: 4.4.0

### Cronjobs
cronjobs:
  - name: Backup
    job: /usr/local/bin/runitor -uuid {{ secret_hc_ambition_db_backup }} -- /home/{{ main_username }}/scripts/db_backup.sh
    user: "{{ main_username }}"
    minute: 0
    hour: 5
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_prune_ambition }} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 0
    hour: 6
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_check_ambition }} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 45
    hour: 5
    day: 1
  - name: Cert Update
    job: /usr/local/bin/runitor -uuid {{ secret_hc_ambition_certs }} -- /home/{{ main_username }}/scripts/certs.sh
    user: root
    minute: 0
    hour: 19
    day: 1,15
  - name: Data Backup
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_backup_ambition }} -- /usr/local/bin/autorestic backup -a -c /home/{{ main_username }}/.autorestic.yml
    user: root
    minute: 15
    hour: 5

### UFW Rules
ufw:
  - comment: 'ssh'
    rule: 'allow'
    port: '22'
    proto: 'any'
    route: 'no'
  - comment: 'reverse proxy'
    rule: 'allow'
    port: '80'
    proto: 'tcp'
    route: 'no'
  - comment: 'reverse proxy'
    rule: 'allow'
    port: '443'
    proto: 'tcp'
    route: 'no'
  - comment: 'iperf'
    rule: 'allow'
    port: '5201'
    proto: 'tcp'
    route: 'no'
  - comment: 'wireguard tunnel'
    rule: 'allow'
    port: '51282'
    proto: 'udp'
    route: 'no'
  - comment: 'gitea'
    rule: 'allow'
    port: '222'
    proto: 'tcp'
    route: 'no'
  - comment: 'portainer'
    rule: 'allow'
    port: '9001'
    proto: 'tcp'
    route: 'no'
  - comment: 'tailscale adapter'
    rule: 'allow'
    interface: tailscale0
    direction: in
    proto: 'any'
    route: 'no'

### Caddy Config
caddy_systemd_capabilities_enabled: true
caddy_systemd_network_dependency: false
caddy_packages:  ["github.com/hslatman/caddy-crowdsec-bouncer", "github.com/greenpau/caddy-security", "github.com/porech/caddy-maxmind-geolocation"]
caddy_conf_dir: /home/{{ main_username }}/caddy
caddy_config: "{{ lookup('template', 'roles/ambition/templates/Caddyfile.j2') }}"

### Autorestic Config
autorestic_config_user: "{{ main_username}}"
autorestic_config_directory: "/home/{{ main_username}}"
autorestic_run_check: false
autorestic_config_yaml:
  version: 2
  backends:
    b2_docker:
      type: b2
      path: "{{ secret_restic_b2_bucket }}:/linode/docker"
      key: "{{ secret_restic_repo_password }}"
      env:
        - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
        - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"
    b2_db:
      type: b2
      path: "{{ secret_restic_b2_bucket }}:/linode/db"
      key: "{{ secret_restic_repo_password }}"
      env:
        - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
        - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"
    b2_certs:
      type: b2
      path: "{{ secret_restic_b2_bucket }}:/linode/certs"
      key: "{{ secret_restic_repo_password }}"
      env:
        - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
        - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"
  locations:
    docker:
      from: '/home/{{ main_username }}/docker'
      to:
        - b2_docker
      options:
        backup:
          exclude:
            - '/home/{{ main_username }}/docker/umami'
            - '/home/{{ main_username }}/docker/gitea/mariadb'
        forget:
          keep-daily: 1
          keep-weekly: 6
          keep-monthly: 3
    db:
      from: '/home/{{ main_username }}/db_backups'
      to:
        - b2_db
      options:
        forget:
          keep-daily: 1
          keep-weekly: 6
          keep-monthly: 3
    certs:
      from: '/home/{{ main_username }}/lego'
      to:
        - b2_certs
      options:
        forget:
          keep-daily: 1
          keep-weekly: 4
