---
target_os: fedora
bootstrap_user: "{{ main_username }}"

### Install packages with grog.package
package_list:
  - name: "@core"
  - name: "@multimedia"
  - name: "@sound-and-video"
  - name: intel-media-driver
  - name: ffmpeg
  - name: audacity
  - name: calibre
  - name: cifs-utils
  - name: curl
  - name: ethtool
  - name: filezilla
  - name: firefox
  - name: flameshot
  - name: flatpak
  - name: freerdp
  - name: gcc
  - name: gimp
  - name: git
  - name: hddtemp
  - name: htop
  - name: iperf3
  - name: kolourpaint
  - name: krename
  - name: libreoffice
  - name: lm_sensors
  - name: mkvtoolnix
  - name: mpv
  - name: nano
  - name: ncdu
  - name: net-tools
  - name: nextcloud-client
  - name: nfs-utils
  - name: pdfarranger
  - name: python
  - name: python-psutil
  - name: python3-devel
  - name: remmina
  - name: restic
  - name: screen
  - name: skanlite
  - name: solaar
  - name: spectacle
  - name: sudo
  - name: thunderbird
  - name: tree
  - name: vlc
  - name: wget
  - name: wireguard-tools
  - name: logiops
  - name: printer-driver-brlaser
  - name: pipx

flatpak_list:
  - name: us.zoom.Zoom
  - name: com.github.IsmaelMartinez.teams_for_linux
  - name: com.github.iwalton3.jellyfin-media-player
  - name: com.mojang.Minecraft
  - name: com.vivaldi.Vivaldi
  - name: md.obsidian.Obsidian
  - name: com.bambulab.BambuStudio
  - name: org.ferdium.Ferdium
  - name: com.system76.Popsicle
  - name: com.jgraph.drawio.desktop
  - name: org.raspberrypi.rpi-imager
  - name: com.moonlight_stream.Moonlight
  - name: io.github.janbar.noson
  - name: io.github.dweymouth.supersonic

### Mounts
mountpoints:
  - path: /mnt/Backup
    source: 192.168.10.20:/volume1/Backup/
    fs: nfs
    opts: "defaults"
  - path: /mnt/NVR
    source: 192.168.10.20:/volume1/BlueIris/
    fs: nfs
    opts: "defaults"
  - path: "/mnt/Media"
    source: "//192.168.1.10/Media"
    fs: cifs
    opts: "_netdev,noauto,nofail,x-systemd.automount,uid=1000,gid=1000,credentials=/home/{{ main_username }}/.smbcredentials"

### Variables
pip_package: python-pip

### Bash Aliases
bash_aliases:
  - alias: c
    command: clear
  - alias: e
    command: exit
  - alias: ssh-remove
    command: ssh-keygen -f /home/{{ main_username }}/.ssh/known_hosts -R $c
  - alias: logi-restart
    command: sudo systemctl restart logid
bash_autorestic: true
bash_systemctl: true
bash_git: true
