---
target_os: ubuntu
hostname: dominion

### Install packages with grog.package
package_list:
  - name: python
  - name: ansible
  - name: sudo
  - name: git
  - name: wget
  - name: make
  - name: sshpass

pull_backup: false