---
target_os: ubuntu
hostname: dominion

### Install packages with grog.package
package_list:
  - name: python3
  - name: curl
  - name: sudo
  - name: git
  - name: wget
  - name: make
  - name: sshpass
  - name: screen

pull_backup: false

### Cronjobs
cronjobs:
  - name: Ansible Update
    job: /usr/local/bin/runitor -uuid {{secret_hc_ansible_update}} -- /home/{{ main_username }}/update.sh
    user: "{{ main_username }}"
    minute: 30
    hour: 19
    weekday: 3
