---
target_os: ubuntu
hostname: dominion

### Install packages with grog.package
package_list:
  - name: python3
  - name: curl
  - name: sudo
  - name: git
  - name: wget
  - name: make
  - name: sshpass
  - name: screen

pull_backup: false