---
target_os: ubuntu
hostname: dominion

### Install packages with grog.package
package_list:
  - name: python3
  - name: curl
  - name: sudo
  - name: git
  - name: wget
  - name: make
  - name: sshpass
  - name: screen

### Pip Packages
pip_packages:
  - ansible
  - yamllint
  - thefuck

pull_backup: false

### Bash Aliases

bash_aliases:
  - alias: c
    command: clear
  - alias: e
    command: exit
  - alias: gitcheck
    command: /bin/bash /home/{{ main_username }}/infra/git-vault-check.sh
  - alias: ssh-remove
    command: ssh-keygen -f /home/{{ main_username }}/.ssh/known_hosts -R $c
bash_systemctl: true
bash_apt: true

### Cronjobs
cronjobs:
  - name: Ansible Update
    job: /usr/local/bin/runitor -uuid {{ secret_hc_ansible_update }} -- /home/{{ main_username }}/update.sh
    user: "{{ main_username }}"
    minute: 30
    hour: 19
    weekday: 3
