---
target_os: ubuntu
hostname: drone

### Install packages with grog.package
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: net-tools
  - name: python
  - name: sudo
  - name: wget

### Pip Packages
pip_packages:
  - thefuck

### Bash Aliases

bash_docker: true
bash_autorestic: false
bash_systemctl: true
bash_apt: true

### Cronjobs
cronjobs:
  - name: Docker Image Prune
    job: /usr/local/bin/runitor -uuid {{ secret_hc_drone_docker_prune }} -- /usr/bin/docker system prune -a -f
    user: "{{ main_username }}"
    minute: 35
    hour: 5
    day: 1,15

### Docker-Compose with ironicbadger.docker_compose_generator
appdata_path: "/home/{{ main_username }}/docker"
containers:
  ###
  - service_name: drone-runner-gh
    container_name: drone-runner-gh
    active: true
    image: drone/drone-runner-docker:1.8.3
    restart: always
    ports:
      - 4300:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=github.ci.fuzzymistborn.com
      - DRONE_RPC_SECRET={{ secret_drone_rpc }}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=Adonalsium-GitHub
    include_global_env_vars: false
  ###
  - service_name: drone-runner-gitea
    container_name: drone-runner-gitea
    active: true
    image: drone/drone-runner-docker:1.8.3
    restart: always
    ports:
      - 4301:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_HOST=gitea.ci.fuzzymistborn.com
      - DRONE_RPC_SECRET={{ secret_drone_rpc }}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=Adonalsium-Gitea
    include_global_env_vars: false
  ###
  - service_name: portainer_agent
    container_name: portainer_agent
    active: true
    image: portainer/agent:2.19.4
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_SECRET={{ secret_portainer_key }}
    include_global_env_vars: false
