---
target_os: ubuntu
hostname: endowment

### Install packages with grog.package
package_list:
  - name: curl
  - name: cifs-utils
  - name: fail2ban
  - name: git
  - name: htop
  - name: lm-sensors
  - name: net-tools
  - name: python
  - name: restic
  - name: rsyslog
  - name: sudo
  - name: wget

smb_mountpoints:
  - path: "/mnt/Media"
    source: "//192.168.30.10/Media"
    fs: cifs
    opts: "defaults,uid=1000,gid=1000,credentials=/home/{{main_username}}/.smbcredentials"

pull_backup: false

# syncthing_ver: v1.18.2
# syncthing_force_install: true

### Telegraf
telegraf_influx_token: "{{secret_telegraf_endowment}}"
telegraf_influx_bucket: Endowment
telegraf_influx_docker: true

### Cronjobs
cronjobs:
  - name: Nextcloud
    job: /home/{{ main_username }}/scripts/nextcloud_cron.sh
    user: "{{ main_username }}"
    minute: '*/5'
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{secret_hc_endowment_purge}} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 30
    hour: 22
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{secret_hc_restic_check_endowment}} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 30
    hour: 2
    day: 1
  - name: Photo Reorg
    job: /usr/local/bin/runitor -uuid {{ secret_hc_photo_reorg }} -- /home/{{ main_username }}/scripts/photos.sh
    user: "{{ main_username }}"
    minute: 0
    hour: 3
  - name: Media Backup
    job: /usr/local/bin/runitor -uuid {{secret_hc_endowment_media}} -- /usr/local/bin/autorestic backup -a -c /home/{{main_username}}/.autorestic.yml
    user: root
    minute: 30
    hour: 0

### Autorestic Config
autorestic_locations:
  - name: docker
    from: '/home/{{main_username}}/docker'
    to: 
      - synology_docker
      - b2_docker
    options:
      forget:
        daily: 1
        weekly: 8
        monthly: 4

autorestic_backends:
  - name: synology_docker
    type: s3
    path: 'http://192.168.30.25:9000/endowment'
    key: "{{ secret_restic_repo_password }}"
    env:
      - AWS_ACCESS_KEY_ID: "{{ secret_minio_s3_access_key_id }}"
      - AWS_SECRET_ACCESS_KEY: "{{ secret_minio_s3_access_key }}"
  - name: b2_docker
    type: b2
    path: '{{ secret_restic_b2_bucket }}:/endowment'
    key: "{{ secret_restic_repo_password }}"
    env:
      - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
      - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"

### Docker-Compose with ironicbadger.docker_compose_generator
appdata_path: "/home/{{ main_username }}/docker"
containers:
  ###
  - service_name: diun
    container_name: diun
    active: true
    image: crazymax/diun:latest
    restart: always
    labels:
      - "diun.enable=true"
      - "diun.regopt=docker.io"
    volumes:
      - "{{ appdata_path }}/diun/data:/data"
      - "{{ appdata_path }}/diun/config.yml:/diun.yml:ro"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      - LOG_JSON=false
    hostname: "{{ hostname }}"
    include_global_env_vars: true
  ###
  - service_name: radarr
    container_name: radarr
    active: true
    image: ghcr.io/linuxserver/radarr
    restart: always
    ports:
      - 7878:7878
    volumes:
      - "{{ appdata_path }}/radarr:/config"
      - /mnt/Media/Movies:/movies
      - /mnt/Media/Kids Movies:/kids_movies
      - /mnt/Media/Parents Movies:/parents_movies
      - "/mnt/scratch/complete:/downloads"
    labels:
      - "diun.enable=true"
      - "diun.regopt=ghcr.io"
    include_global_env_vars: true
  ###
  - service_name: radarr_uhd
    container_name: radarr_uhd
    active: true
    image: ghcr.io/linuxserver/radarr
    restart: always
    ports:
      - 7879:7878
    volumes:
      - "{{ appdata_path }}/radarr_uhd:/config"
      - /mnt/Media/UHD:/uhd
      - "/mnt/scratch/complete:/downloads"
    labels:
      - "diun.enable=true"
      - "diun.regopt=ghcr.io"
    include_global_env_vars: true
  ###
  - service_name: sonarr
    container_name: sonarr
    active: true
    image: ghcr.io/linuxserver/sonarr
    restart: always
    ports:
      - 8989:8989
    volumes:
      - "{{ appdata_path }}/sonarr:/config"
      - /mnt/Media/TV Shows:/tv
      - /mnt/Media/Kids TV:/kids_tv
      - /mnt/Media/Parents TV:/parents_tv
      - "/mnt/scratch/complete:/downloads"
    labels:
      - "diun.enable=true"
      - "diun.regopt=ghcr.io"
    include_global_env_vars: true
  ###
  - service_name: prowlarr
    container_name: prowlarr
    active: true
    image: ghcr.io/linuxserver/prowlarr:develop
    restart: always
    ports:
      - 9696:9696
    volumes:
      - "{{ appdata_path }}/prowlarr:/config"
    labels:
      - "diun.enable=true"
      - "diun.regopt=ghcr.io"
    include_global_env_vars: true
  ###
  - service_name: ombi
    container_name: ombi
    active: true
    image: ghcr.io/linuxserver/ombi:latest
    restart: always
    ports:
      - 3579:3579
    volumes:
      - "{{ appdata_path }}/ombi/config:/config"
    labels:
      - "diun.enable=true"
      - "diun.regopt=ghcr.io"
    include_global_env_vars: true
  ###
  - service_name: sabnzbd
    container_name: sabnzbd
    active: true
    image: ghcr.io/linuxserver/sabnzbd
    restart: always
    ports:
      - 8060:8080
      - 9080:9090
    volumes:
      - "{{ appdata_path }}/sabnzb:/config"
      - "/mnt/scratch/complete:/downloads"
      - "/mnt/scratch/incomplete:/incomplete-downloads"
    labels:
      - "diun.enable=true"
      - "diun.regopt=ghcr.io"
    include_global_env_vars: true
  ###
  - service_name: lms
    container_name: logitech_media_server
    active: true
    image: fuzzymistborn/lms:latest
    restart: always
    network_mode: host
    volumes:
      - "{{ appdata_path }}/lms/data:/var/lib/squeezeboxserver"
      - "{{ appdata_path }}/lms/logs:/var/log/squeezeboxserver"
      - "{{ appdata_path }}/lms/playlists:/mnt/playlists"
      - /mnt/Media/Music:/mnt/Media/Music:ro
    labels:
      - "diun.enable=true"
      - "diun.regopt=docker.io"
    include_global_env_vars: false
  ###
  - service_name: nextcloud
    container_name: nextcloud
    active: true
    image: nextcloud
    restart: always
    ports:
      - 3491:80
      - 3492:443
    volumes:
      - "{{ appdata_path }}/nextcloud_docker/apps:/var/www/html/apps"
      - "{{ appdata_path }}/nextcloud_docker/html:/var/www/html"
      - "{{ appdata_path }}/nextcloud_docker/config:/var/www/html/config"
      - "{{ appdata_path }}/nextcloud_docker/data:/var/www/html/data"
      - /mnt/Media/:/mnt/Media/
    labels:
      - "diun.enable=true"
      - "diun.regopt=docker.io"
    mem_limit: 1000M
    include_global_env_vars: true
  ###
  - service_name: photoview
    container_name: photoview
    active: true
    image: viktorstrate/photoview:latest
    restart: always
    network_mode: host
    volumes:
      - "{{ appdata_path }}/photoview/api_cache:/app/cache"
      - /mnt/Media/Photos:/photos:ro
    environment:
      - PHOTOVIEW_DATABASE_DRIVER=mysql
      - PHOTOVIEW_MYSQL_URL=photoview:{{ secret_photoview_db_pass }}@tcp(192.168.30.14:3310)/photoview
      - PHOTOVIEW_LISTEN_IP=photoview
      - PHOTOVIEW_LISTEN_PORT=8000
      - PHOTOVIEW_MEDIA_CACHE=/app/cache
      - GODEBUG=asyncpreemptoff=1
      - MAPBOX_TOKEN={{ secret_photoview_mapbox_token }}
    labels:
      - "diun.enable=true"
      - "diun.regopt=docker.io"
    include_global_env_vars: false
  ###
  - service_name: syncthing
    container_name: syncthing
    active: true
    image: ghcr.io/linuxserver/syncthing
    restart: always
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    volumes:
      - "{{ appdata_path }}/syncthing:/config"
      - /mnt/Media/Files/Roms/Retropie:/retropie
    labels:
      - "diun.enable=true"
      - "diun.regopt=ghcr.io"
    include_global_env_vars: true
  ###
  - service_name: remote-api
    container_name: remote-api
    active: true
    image: kekru/docker-remote-api-tls:v0.3.0
    restart: always
    ports:
      - 2376:443
    volumes:
      - "{{ appdata_path }}/docker-api:/data/certs"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CREATE_CERTS_WITH_PW={{ secret_docker_api_tls }}
      - CERT_HOSTNAME=docker-remote.local
    labels:
      - "diun.enable=true"
      - "diun.regopt=docker.io"
    include_global_env_vars: false
  ###
  - service_name: portainer_agent
    container_name: portainer_agent
    active: true
    image: portainer/agent
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_SECRET={{secret_portainer_key}}
    labels:
      - "diun.enable=true"
      - "diun.regopt=docker.io"
    include_global_env_vars: false
