---
target_os: ubuntu
hostname: endowment

### Install packages with grog.package
package_list:
  - name: acl
  - name: curl
  - name: cifs-utils
  - name: git
  - name: htop
  - name: lm-sensors
  - name: net-tools
  - name: python
  - name: restic
  - name: sudo
  - name: wget

smb_mountpoints:
  - path: "/mnt/Media"
    source: "//192.168.1.10/Media"
    fs: cifs
    opts: "defaults,uid=1000,gid=1000,credentials=/home/{{ main_username }}/.smbcredentials"

pull_backup: false

### LNXLink
lnxlink_diskuse: true

### Bash Aliases
bash_docker: true
bash_autorestic: true
bash_systemctl: true
bash_apt: true

### Cronjobs
cronjobs:
  - name: Nextcloud
    job: /home/{{ main_username }}/scripts/nextcloud_cron.sh
    user: "{{ main_username }}"
    minute: '*/5'
  - name: Restart Jellyfin
    job: docker container restart jellyfin > /dev/null 2>&1
    user: "{{ main_username }}"
    hour: 2
    minute: 30
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_prune_endowment }} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 30
    hour: 22
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_check_endowment }} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 30
    hour: 2
    day: 1
  - name: Photo Reorg
    job: /usr/local/bin/runitor -uuid {{ secret_hc_photo_reorg }} -- /home/{{ main_username }}/scripts/photos.sh
    user: "{{ main_username }}"
    minute: 0
    hour: 3
  - name: Media Backup
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_backup_endowment }} -- /usr/local/bin/autorestic backup -a -c /home/{{ main_username }}/.autorestic.yml
    user: root
    minute: 30
    hour: 0

### Autorestic Config
autorestic_config_user: "{{ main_username}}"
autorestic_config_directory: /home/"{{ main_username}}"
autorestic_run_check: false
autorestic_config_yaml:
  version: 2
  backends:
    local_docker:
      type: rest
      path: 'http://192.168.1.5:8500/endowment'
      key: "{{ secret_restic_repo_password }}"
      rest:
        user: "{{ secret_restic_rest_user }}"
        password: "{{ secret_restic_rest_password }}"
    b2_docker:
      type: b2
      path: "{{ secret_restic_b2_bucket }}:/endowment"
      key: "{{ secret_restic_repo_password }}"
      env:
        - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
        - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"
  locations:
    docker:
      from: '/home/{{ main_username }}/docker'
      to:
        - local_docker
        - b2_docker
      options:
        backup:
          exclude:
            - 'transcodes'
        forget:
          keep-daily: 1
          keep-weekly: 8
          keep-monthly: 4
