---
target_os: nobara
bootstrap_user: "{{ main_username }}"
webhook_user: "{{ main_username }}"

### Install custom packages
package_list:
  - name: dolphin-emu
  - name: mupen64plus
  - name: openssh

whimsy_flatpak_list:
  - name: com.mojang.Minecraft
  - name: net.pcsx2.PCSX2
  - name: org.duckstation.DuckStation
  - name: com.steamgriddb.steam-rom-manager

### Bash Aliases
bash_aliases:
  - alias: c
    command: clear
  - alias: e
    command: exit
  - alias: ssh-remove
    command: ssh-keygen -f /home/{{ main_username }}/.ssh/known_hosts -R $c
bash_autorestic: false
bash_systemctl: true
bash_pacman: false
bash_yay: false
bash_git: false

### Mounts
mountpoints:
  - path: "/mnt/Media"
    source: "//192.168.1.10/Media"
    fs: cifs
    opts: "_netdev,noauto,nofail,x-systemd.automount,uid=1000,gid=1000,credentials=/home/{{ main_username }}/.smbcredentials"

data_disks:
  - path: /mnt/Games_Team
    source: /dev/disk/by-id/ata-TEAM_T253X2001T_TPBF2006200010200009-part1
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/Games_Crucial
    source: /dev/disk/by-id/ata-CT1000MX500SSD1_2252E6976407-part1
    fs: ext4
    opts: defaults
    content: true

### Gnome Desktop Settings
gnome_theme_settings_string:
  - key: /org/gnome/desktop/session/idle-delay
    value: 'uint32 0'

gnome_theme_settings_value:
  - key: /org/gnome/desktop/screensaver/lock-enabled
    value: "false"
  - key: /org/gnome/desktop/interface/enable-hot-corners
    value: "false"
