---
target_os: fedora
hostname: hoid
bootstrap_user: "{{ main_username }}"
pull_backup: false

### LNXLink
lnxlink_shutdown: true
lnxlink_diskuse: true
lnxlink_desktop: true

### Autorestic Config
autorestic_config_user: "{{ main_username}}"
autorestic_config_directory: /home/"{{ main_username}}"
autorestic_run_check: false
autorestic_config_yaml:
  version: 2
  backends:
    local_files:
      type: rest
      path: 'http://192.168.1.5:8500/hoid'
      key: "{{ secret_restic_repo_password }}"
      rest:
        user: "{{ secret_restic_rest_user }}"
        password: "{{ secret_restic_rest_password }}"
  locations:
    files:
      from: /home/{{ main_username }}
      to:
        - local_files
      options:
        backup:
          exclude:
            - '.cache*'
            - 'Nextcloud'
            - 'Downloads'
            - 'git'
            - '*steam*'
        forget:
          keep-daily: 3
          keep-weekly: 4
          keep-monthly: 2

desktop_hc_prune_id: "{{ secret_hc_restic_prune_hoid }}"
desktop_hc_backup_id: "{{ secret_hc_restic_backup_hoid }}"

### Bash Aliases
bash_aliases:
  - alias: fingerprint-enable
    command: sudo authselect enable-feature with-fingerprint
  - alias: fingerprint-disable
    command: sudo authselect disable-feature with-fingerprint

### Cronjobs
cronjobs:
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_check_hoid }} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 20
    hour: 20
    day: 1