---
target_os: ubuntu
hostname: honor

### Install packages with grog.package
package_list:
  - name: curl
  - name: htop
  - name: net-tools
  - name: sudo
  - name: restic
  - name: wget
  - name: wireguard

pull_backup: false
# lego_ver: 4.4.0

### Bash Aliases

bash_docker: true
bash_autorestic: true
bash_systemctl: true
bash_apt: true

### Cronjobs
cronjobs:
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_prune_honor }} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 15
    hour: 22
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_check_honor }} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 15
    hour: 2
    day: 1
  - name: Media Backup
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_backup_honor }} -- /usr/local/bin/autorestic backup -a -c /home/{{ main_username }}/.autorestic.yml
    user: root
    minute: 15
    hour: 0
  - name: Cert Update
    job: /usr/local/bin/runitor -uuid {{ secret_hc_honor_certs }} -- /home/{{ main_username }}/certs.sh
    user: root
    minute: 0
    hour: 19
    day: 1,15
  - name: Wireguard Tunnel Check/Restore
    job: /home/{{ main_username }}/wg-check.sh
    user: root
    minute: '*/5'
  - name: Ambition DynDNS
    job: /usr/local/bin/runitor -uuid {{ secret_hc_ambition_dyndns_check }} -- /home/{{ main_username }}/ddns_vps.sh
    user: "{{ main_username }}"
    minute: '*/10'

### Autorestic Config
autorestic_config_user: "{{ main_username}}"
autorestic_config_directory: "/home/{{ main_username}}"
autorestic_run_check: false
autorestic_config_yaml:
  version: 2
  backends:
    local_docker:
      type: rest
      path: 'http://192.168.1.5:8500/honor'
      key: "{{ secret_restic_repo_password }}"
      rest:
        user: "{{ secret_restic_rest_user }}"
        password: "{{ secret_restic_rest_password }}"
    b2_docker:
      type: b2
      path: "{{ secret_restic_b2_bucket }}:/honor"
      key: "{{ secret_restic_repo_password }}"
      env:
        - B2_ACCOUNT_ID: "{{ secret_restic_b2_account_id }}"
        - B2_ACCOUNT_KEY: "{{ secret_restic_b2_account_key }}"
  locations:
    docker:
      from: '/home/{{ main_username }}/docker'
      to:
        - local_docker
        - b2_docker
      options:
        forget:
          keep-daily: 1
          keep-weekly: 8
          keep-monthly: 3

### Caddy Config
caddy_systemd_capabilities_enabled: true
caddy_systemd_network_dependency: false
caddy_packages:  ["github.com/greenpau/caddy-security"]
caddy_conf_dir: /home/{{ main_username }}/caddy
caddy_config: "{{ lookup('template', 'roles/honor/templates/Caddyfile.j2') }}"
