---
target_os: endeavour_os
hostname: kelsier

### Install packages with grog.package
package_list:
  - name: curl
  - name: cronie
  - name: htop
  - name: net-tools
  - name: ethtool
  - name: sudo
  - name: wget
  - name: wireguard-tools
  - name: restic
  - name: git
  - name: lm_sensors
  - name: python
  - name: screen
  - name: wget
  - name: ncdu
  - name: cifs-utils
  - name: nut
  - name: openssh
  - name: virtualbox
  - name: calibre
  - name: gimp
  - name: mkvtoolnix-gui
  - name: remmina
  - name: filezilla
  - name: flameshot
  - name: gedit
  - name: gparted
  - name: kolourpaint
  - name: lutris
  - name: mpv
  - name: nextcloud-client
  - name: pdfarranger
  - name: thunderbird
  - name: vlc
  - name: handbrake
  - name: ansible
  - name: veracrypt
  - name: flatpak
  - name: hddtemp
  - name: iperf3
  - name: nano
  - name: nfs-utils
  - name: ntfs-3g
  - name: pipewire
  - name: steam
  - name: thunderbird
  - name: firefox
  - name: wine

data_disks:
  - {path: /mnt/Games, source: /dev/disk/by-id/ata-TEAM_T253X2001T_TPBF2006200010200009-part1, fs: ext4, opts: defaults, content: true}

nfs_mount:
  - {path: /mnt/Backup, source: 192.168.10.20:/volume1/Backup/, fs: nfs, opts: defaults, content: false}
  - {path: /mnt/NVR, source: 192.168.10.20:/volume1/BlueIris/, fs: nfs, opts: defaults, content: false}

smb_mountpoints:
  - {path: "/mnt/Media", source: "//192.168.30.10/Media", fs: cifs, opts: "defaults,uid=1000,gid=1000,credentials=/home/{{main_username}}/.smbcredentials"}
  - {path: "/home/{{main_username}}/RetroPie", source: "//192.168.30.10/Media/Files/Roms/Retropie", fs: cifs, opts: "defaults,uid=1000,gid=1000,credentials=/home/{{main_username}}/.smbcredentials"}

### Variables
install_nut: false
pull_backup: false

pip_package: python-pip

### Cronjobs
cronjobs:
  - name: App Backup
    job: /mnt/Backup/Kelsier/app_backup.sh
    user: "{{ main_username }}"
    minute: 0
    hour: 19
    day: '*/3'
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{secret_hc_kelsier_purge}} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 0
    hour: 20
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{secret_hc_restic_check_kelsier}} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 0
    hour: 19
    day: 1
  - name: Media Backup
    job: /usr/local/bin/runitor -uuid {{secret_hc_kelsier_media}} -- /usr/local/bin/autorestic backup -a -c /home/{{main_username}}/.autorestic.yml
    user: root
    minute: 0
    hour: 21
    weekday: 0,3,5
