---
target_os: endeavour_os
hostname: kelsier
bootstrap_user: "{{ main_username }}"

### Install packages with grog.package
package_list:
  - name: dragon
    state: absent
  - name: plank
    state: absent
  - name: gwenview
    state: absent
  - name: ansible
  - name: bluedevil
  - name: bluez
  - name: bluez-utils
  - name: calibre
  - name: cifs-utils
  - name: cronie
  - name: curl
  - name: ethtool
  - name: filezilla
  - name: firefox
  - name: flameshot
  - name: flatpak
  - name: gedit
  - name: gimp
  - name: git
  - name: gparted
  - name: handbrake
  - name: hddtemp
  - name: htop
  - name: iperf3
  - name: img2pdf
  - name: kcharselect
  - name: kdialog
  - name: kdeplasma-addons
  - name: kolourpaint
  - name: krename
  - name: kwalletmanager
  - name: latte-dock
  - name: libreoffice-still
  - name: libvncserver
  - name: lm_sensors
  - name: lutris
  - name: mkvtoolnix-gui
  - name: mpv
  - name: nano
  - name: ncdu
  - name: net-tools
  - name: nextcloud-client
  - name: nfs-utils
  - name: nomacs
  - name: noto-fonts-emoji
  - name: nut
  - name: nvidia-settings
  - name: openssh
  - name: pdfarranger
  - name: pipewire
  - name: pipewire-alsa
  - name: pipewire-jack
  - name: pipewire-zeroconf
  - name: pipewire-pulse
  - name: plasma-browser-integration
  - name: plasma-systemmonitor
  - name: python
  - name: restic
  - name: retroarch
  - name: screen
  - name: scrot
  - name: skanlite
  - name: spectacle
  - name: steam
  - name: sudo
  - name: system-config-printer
  - name: tailscale
  - name: thunderbird
  - name: tree
  - name: veracrypt
  - name: virtualbox
  - name: virtualbox-guest-iso
  - name: virtualbox-host-dkms
  - name: vivaldi
  - name: vlc
  - name: wget
  - name: wine
  - name: winetricks
  - name: wireguard-tools
  - name: xdg-desktop-portal
  - name: xdg-desktop-portal-kde

aur_package_list:
  - name: antimicrox
  - name: bauh
  - name: brother-hl2270dw
  - name: crossover
  - name: deezer
  - name: dxvk-bin
#  - name: epson-perfection-v10-v100-scanner-driver-aio
  - name: esphome
  - name: gwe
  - name: heroic-games-launcher-bin
  - name: jellyfin-media-player
  #- name: lib32-nvidia-utils
  - name: logiops
  - name: mqtt-explorer-appimage  # Other package broken
  - name: pegasus-frontend-git
  - name: polymc
  - name: popsicle
  - name: python-esphome-dashboard
  - name: remmina-git
  - name: rpi-imager-bin
  - name: skyscraper-git
  - name: squeezelite
  - name: telegraf
  - name: timeshift
  - name: timeshift-autosnap
  - name: ventoy
  - name: visual-studio-code-bin
  - name: zoom
  # - ckan  # Currently broken, use Mono
  - name: ferdium-bin

### Pip Packages
pip_packages:
  - thefuck

data_disks:
  - path: /mnt/Games
    source: /dev/disk/by-id/ata-TEAM_T253X2001T_TPBF2006200010200009-part1
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/Games_HDD
    source: /dev/disk/by-id/ata-WDC_WD15EZRX-00DC0B0_WD-WMC300346947-part1
    fs: ext4
    opts: defaults
    content: true

nfs_mount:
  - path: /mnt/Backup
    source: 192.168.10.20:/volume1/Backup/
    fs: nfs
    opts: "_netdev,noauto,nofail,x-systemd.automount"
  - path: /mnt/NVR
    source: 192.168.10.20:/volume1/BlueIris/
    fs: nfs
    opts: "_netdev,noauto,nofail,x-systemd.automount"

smb_mountpoints:
  - path: "/mnt/Media"
    source: "//192.168.1.20/Media"
    fs: cifs
    opts: "_netdev,noauto,nofail,x-systemd.automount,uid=1000,gid=1000,credentials=/home/{{ main_username }}/.smbcredentials"

### Variables
install_nut: true
pull_backup: false

pip_package: python-pip

### Bash Aliases
bash_aliases:
  - alias: c
    command: clear
  - alias: e
    command: exit
  - alias: ssh-remove
    command: ssh-keygen -f /home/{{ main_username }}/.ssh/known_hosts -R $c
  - alias: logi-restart
    command: sudo systemctl restart logid
  - alias: nut
    command: sudo upsdrvctl start && sudo upsd
  - alias: nut-reload
    command: sudo upsdrvctl start && sudo upsd -c reload
bash_autorestic: true
bash_systemctl: true
bash_pacman: true
bash_yay: true
bash_git: true

### Syncthing/Retroarch
retroarch_roms_dir: /mnt/Games/ROMs
retroarch_config_dir: /home/{{ main_username }}/.config/retroarch

pegasus_roms_dir: "{{ retroarch_roms_dir }}"

syncthing_api_key: "{{ secret_syncthing_api_kelsier }}"
syncthing_device_id: "{{ secret_syncthing_kelsier_device }}"
syncthing_gui_authentication: true
syncthing_gui_user: "{{ main_username }}"
syncthing_gui_pass: "{{ secret_syncthing_gui_pass }}"
syncthing_user: "{{ main_username }}"

syncthing_folders:
  - id: "{{ secret_syncthing_sys_folder_id }}"
    label: "RetroArch - System"
    path: "{{ retroarch_config_dir }}"
    type: "sendreceive"  # options are 'sendreceive' 'sendonly' and 'receiveonly'
    rescanInterval: 600  # time in seconds
    devices:
      - "{{ secret_syncthing_retroarchtv_device }}"
      - "{{ secret_syncthing_adonalsium_device }}"
      - "{{ secret_syncthing_steamdeck_device }}"
  - id: "{{ secret_syncthing_rom_folder_id }}"
    label: "RetroArch - ROMs"
    path: "{{ retroarch_roms_dir }}"
    type: "receiveonly"  # options are 'sendreceive' 'sendonly' and 'receiveonly'
    rescanInterval: 600  # time in seconds
    devices:
      - "{{ secret_syncthing_adonalsium_device }}"

syncthing_devices:
  - id: "{{ secret_syncthing_adonalsium_device }}"
    name: adonalsium
    address: tcp://192.168.1.20:22000
  - id: "{{ secret_syncthing_retroarchtv_device }}"
    name: retroarch-tv
    address: tcp://192.168.10.40:22000
  - id: "{{ secret_syncthing_steamdeck_device }}"
    name: steamdeck
    address: tcp://192.168.10.125:22000

### Telegraf
telegraf_influx_token: "{{ secret_telegraf_kelsier }}"
telegraf_influx_bucket: Kelsier
telegraf_influx_disk_mounts: '"/","/mnt/Games","/mnt/Games_HDD"'

### Autorestic Config
autorestic_config_yaml:
  version: 2
  backends:
    synology_docker:
      type: s3
      path: 'http://192.168.10.20:9000/kelsier'
      key: "{{ secret_restic_repo_password }}"
      env:
        - AWS_ACCESS_KEY_ID: "{{ secret_minio_s3_access_key_id }}"
        - AWS_SECRET_ACCESS_KEY: "{{ secret_minio_s3_access_key }}"
  locations:
    docker:
      from: /home/{{ main_username }}
      to:
        - synology_docker
      options:
        backup:
          exclude:
            - '.cache*'
            - 'Nextcloud'
            - 'Downloads'
            - 'git'
            - '*steam*'
        forget:
          keep-daily: 3
          keep-weekly: 4
          keep-monthly: 2

### Cronjobs
cronjobs:
  - name: App Backup
    job: /mnt/Backup/Kelsier/app_backup.sh
    user: "{{ main_username }}"
    minute: 0
    hour: 19
    day: '*/3'
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{ secret_hc_kelsier_purge }} -- /usr/local/bin/autorestic exec -a -- forget --keep-daily 3 --keep-weekly 4 --keep-monthly 2 --prune
#    job: /usr/local/bin/runitor -uuid {{ secret_hc_kelsier_purge }} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 0
    hour: 20
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_check_kelsier }} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 0
    hour: 19
    day: 1
  - name: Media Backup
    job: /usr/local/bin/runitor -uuid {{ secret_hc_kelsier_media }} -- /usr/local/bin/autorestic backup -a -c /home/{{ main_username }}/.autorestic.yml
    user: root
    minute: 0
    hour: 21
    weekday: 0,3,5
