---
target_os: endeavour_os
hostname: kelsier
bootstrap_user: "{{ main_username }}"
webhook_user: "{{ main_username }}"

### Install custom packages
kelsier_package_list:
  - name: lib32-vulkan-radeon
  - name: lutris
  - name: mesa
  - name: mkvtoolnix-gui
  - name: retroarch
  - name: steam
  - name: wine
  - name: winetricks
  - name: vulkan-radeon

kelsier_aur_package_list:
  - name: antimicrox
  - name: dxvk-bin
  - name: heroic-games-launcher-bin
  - name: pegasus-frontend-git
  - name: proton-ge-custom-bin
  - name: polymc
  - name: skyscraper-git
  # - ckan  # Currently broken, use Mono

### Pip Packages
pip_packages:
  - thefuck

data_disks:
  - path: /mnt/Games
    source: /dev/disk/by-id/ata-TEAM_T253X2001T_TPBF2006200010200009-part1
    fs: ext4
    opts: defaults
    content: true
  - path: /mnt/Games_HDD
    source: /dev/disk/by-id/ata-WDC_WD15EZRX-00DC0B0_WD-WMC300346947-part1
    fs: ext4
    opts: defaults
    content: true

### Variables
pull_backup: false
autorestic_run_check: false
pip_package: python-pip

### Bash Aliases
bash_aliases:
  - alias: c
    command: clear
  - alias: e
    command: exit
  - alias: ssh-remove
    command: ssh-keygen -f /home/{{ main_username }}/.ssh/known_hosts -R $c
  - alias: logi-restart
    command: sudo systemctl restart logid
  - alias: nut
    command: sudo upsdrvctl start && sudo upsd
  - alias: nut-reload
    command: sudo upsdrvctl start && sudo upsd -c reload
bash_autorestic: true
bash_systemctl: true
bash_pacman: true
bash_yay: true
bash_git: true

### Syncthing/Retroarch
retroarch_roms_dir: /mnt/Games/ROMs
retroarch_config_dir: /home/{{ main_username }}/.config/retroarch

pegasus_roms_dir: "{{ retroarch_roms_dir }}"

syncthing_api_key: "{{ secret_syncthing_api_kelsier }}"
syncthing_device_id: "{{ secret_syncthing_kelsier_device }}"
syncthing_gui_authentication: true
syncthing_gui_user: "{{ main_username }}"
syncthing_gui_pass: "{{ secret_syncthing_gui_pass }}"
syncthing_user: "{{ main_username }}"

syncthing_folders:
  - id: "{{ secret_syncthing_sys_folder_id }}"
    label: "RetroArch - System"
    path: "{{ retroarch_config_dir }}"
    type: "sendreceive"  # options are 'sendreceive' 'sendonly' and 'receiveonly'
    rescanInterval: 600  # time in seconds
    devices:
      - "{{ secret_syncthing_retroarchtv_device }}"
      - "{{ secret_syncthing_adonalsium_device }}"
      - "{{ secret_syncthing_steamdeck_device }}"
  - id: "{{ secret_syncthing_rom_folder_id }}"
    label: "RetroArch - ROMs"
    path: "{{ retroarch_roms_dir }}"
    type: "receiveonly"  # options are 'sendreceive' 'sendonly' and 'receiveonly'
    rescanInterval: 600  # time in seconds
    devices:
      - "{{ secret_syncthing_adonalsium_device }}"

syncthing_devices:
  - id: "{{ secret_syncthing_adonalsium_device }}"
    name: adonalsium
    address: tcp://192.168.1.10:22000
  - id: "{{ secret_syncthing_retroarchtv_device }}"
    name: retroarch-tv
    address: tcp://192.168.10.40:22000
  - id: "{{ secret_syncthing_steamdeck_device }}"
    name: steamdeck
    address: tcp://192.168.10.125:22000

### Telegraf
telegraf_influx_token: "{{ secret_telegraf_kelsier }}"
telegraf_influx_bucket: Kelsier
telegraf_influx_disk_mounts: '"/","/mnt/Games","/mnt/Games_HDD"'

### Autorestic Config
autorestic_config_yaml:
  version: 2
  backends:
    synology_docker:
      type: s3
      path: 'http://192.168.10.20:9000/kelsier'
      key: "{{ secret_restic_repo_password }}"
      env:
        - AWS_ACCESS_KEY_ID: "{{ secret_minio_s3_access_key_id }}"
        - AWS_SECRET_ACCESS_KEY: "{{ secret_minio_s3_access_key }}"
  locations:
    docker:
      from: /home/{{ main_username }}
      to:
        - synology_docker
      options:
        backup:
          exclude:
            - '.cache*'
            - 'Nextcloud'
            - 'Downloads'
            - 'git'
            - '*steam*'
        forget:
          keep-daily: 3
          keep-weekly: 4
          keep-monthly: 2

### Cronjobs
cronjobs:
  - name: App Backup
    job: /mnt/Backup/Kelsier/app_backup.sh
    user: "{{ main_username }}"
    minute: 0
    hour: 19
    day: '*/3'
  - name: Restic Prune
#    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_prune_kelsier }} -- /usr/local/bin/autorestic exec -a -- forget --keep-daily 3 --keep-weekly 4 --keep-monthly 2 --prune
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_prune_kelsier }} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 0
    hour: 20
    weekday: 1
  - name: Restic Backup
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_backup_kelsier }} -- /usr/local/bin/autorestic backup -a -c /home/{{ main_username }}/.autorestic.yml
    user: root
    minute: 0
    hour: 21