---
target_os: endeavour_os
hostname: kelsier

### Install packages with grog.package
package_list:
  - name: dragon
    state: absent
  - name: dolphin
    state: absent
  - name: plank
    state: absent
  - name: gwenview
    state: absent
  - name: curl
  - name: cronie
  - name: htop
  - name: net-tools
  - name: ethtool
  - name: sudo
  - name: wget
  - name: wireguard-tools
  - name: restic
  - name: git
  - name: nautilus
  - name: lm_sensors
  - name: python
  - name: screen
  - name: wget
  - name: ncdu
  - name: cifs-utils
  - name: nut
  - name: openssh
  - name: virtualbox
  - name: virtualbox-host-dkms
  - name: virtualbox-ext-oracle
  - name: virtualbox-guest-iso
  - name: calibre
  - name: gimp
  - name: mkvtoolnix-gui
  - name: filezilla
  - name: flameshot
  - name: gedit
  - name: gparted
  - name: kolourpaint
  - name: lutris
  - name: mpv
  - name: nextcloud-client
  - name: pdfarranger
  - name: thunderbird
  - name: vlc
  - name: handbrake
  - name: ansible
  - name: veracrypt
  - name: flatpak
  - name: hddtemp
  - name: iperf3
  - name: nano
  - name: nfs-utils
  - name: ntfs-3g
  - name: pipewire-pulse
  - name: steam
  - name: thunderbird
  - name: firefox
  - name: wine
  - name: plasma-browser-integration
  - name: libreoffice-still
  - name: system-config-printer
  - name: vivaldi
  - name: latte-dock
  - name: libvncserver
  - name: scrot
  - name: spectacle
  - name: kdialog
  - name: nomacs
  - name: skanlite

data_disks:
  - path: /mnt/Games
    source: /dev/disk/by-id/ata-TEAM_T253X2001T_TPBF2006200010200009-part1
    fs: ext4
    opts: defaults
    content: true

nfs_mount:
  - path: /mnt/Backup
    source: 192.168.10.20:/volume1/Backup/
    fs: nfs
    opts: "_netdev,noauto,nofail,x-systemd.automount"
  - path: /mnt/NVR
    source: 192.168.10.20:/volume1/BlueIris/
    fs: nfs
    opts: "_netdev,noauto,nofail,x-systemd.automount"

smb_mountpoints:
  - path: "/mnt/Media"
    source: "//192.168.1.20/Media"
    fs: cifs
    opts: "_netdev,noauto,nofail,x-systemd.automount,uid=1000,gid=1000,credentials=/home/{{main_username}}/.smbcredentials"
  - path: "/home/{{main_username}}/RetroPie"
    source: "//192.168.1.20/Media/Files/Roms/Retropie"
    fs: cifs
    opts: "_netdev,noauto,nofail,x-systemd.automount,uid=1000,gid=1000,credentials=/home/{{main_username}}/.smbcredentials"

### Variables
install_nut: true
pull_backup: false

pip_package: python-pip

### Telegraf
telegraf_influx_token: "{{secret_telegraf_kelsier}}"
telegraf_influx_bucket: Kelsier
telegraf_influx_disk_mounts: '"/","/mnt/Games"'

### Autorestic Config
autorestic_locations:
  - name: docker
    from: '/home/{{main_username}}'
    to:
      - synology_docker
    options:
      backup:
        exclude:
          - "'.cache*'"
          - "'Nextcloud'"
          - "'Downloads'"
          - "'git'"
          - "'*steam*'"
      forget:
        daily: 7
        weekly: 4
        monthly: 2

autorestic_backends:
  - name: synology_docker
    type: s3
    path: 'http://192.168.10.20:9000/kelsier'
    key: "{{ secret_restic_repo_password }}"
    env:
      - "AWS_ACCESS_KEY_ID: {{ secret_minio_s3_access_key_id }}"
      - "AWS_SECRET_ACCESS_KEY: {{ secret_minio_s3_access_key }}"

### Cronjobs
cronjobs:
  - name: App Backup
    job: /mnt/Backup/Kelsier/app_backup.sh
    user: "{{ main_username }}"
    minute: 0
    hour: 19
    day: '*/3'
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{secret_hc_kelsier_purge}} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 0
    hour: 20
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{secret_hc_restic_check_kelsier}} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 0
    hour: 19
    day: 1
  - name: Media Backup
    job: /usr/local/bin/runitor -uuid {{secret_hc_kelsier_media}} -- /usr/local/bin/autorestic backup -a -c /home/{{main_username}}/.autorestic.yml
    user: root
    minute: 0
    hour: 21
    weekday: 0,3,5
