---
target_os: ubuntu
hostname: mercy

### Install packages with grog.package
package_list:
  - name: curl
  - name: htop
  - name: git
  - name: net-tools
  - name: sudo
  - name: wget
  - name: libreadline-dev
  - name: libconfig-dev
  - name: libssl-dev
  - name: lua5.2
  - name: liblua5.2-dev
  - name: libevent-dev
  - name: libjansson-dev
  - name: libpython-dev
  - name: libpython3-dev
  - name: libgcrypt-dev
  - name: zlib1g-dev
  - name: lua-lgi
  - name: make
  - name: python
  - name: python-pip
  - name: restic

pull_backup: false

### Autorestic Config
autorestic_config_yaml:
  version: 2
  backends:
    synology_plugins:
      type: s3
      path: 'http://192.168.30.25:9000/mercy/plugins'
      key: "{{ secret_restic_repo_password }}"
      env:
        - AWS_ACCESS_KEY_ID: "{{ secret_minio_s3_access_key_id }}"
        - AWS_SECRET_ACCESS_KEY: "{{ secret_minio_s3_access_key }}"
    synology_local:
      type: s3
      path: 'http://192.168.30.25:9000/mercy/local'
      key: "{{ secret_restic_repo_password }}"
      env:
        - AWS_ACCESS_KEY_ID: "{{ secret_minio_s3_access_key_id }}"
        - AWS_SECRET_ACCESS_KEY: "{{ secret_minio_s3_access_key }}"
    synology_telegram:
      type: s3
      path: 'http://192.168.30.25:9000/mercy/telegram'
      key: "{{ secret_restic_repo_password }}"
      env:
        - AWS_ACCESS_KEY_ID: "{{ secret_minio_s3_access_key_id }}"
        - AWS_SECRET_ACCESS_KEY: "{{ secret_minio_s3_access_key }}"
  locations:
    plugins:
      from: '/home/{{ main_username }}/hangoutsbot/hangupsbot/plugins'
      to:
        - synology_plugins
      options:
        forget:
          keep-last: 10
    local:
      from: '/home/{{ main_username }}/.local/share/hangupsbot'
      to:
        - synology_local
      options:
        forget:
          keep-last: 10
    telegram:
      from: '/home/{{ main_username }}/.telegram-cli'
      to:
        - synology_telegram
      options:
        forget:
          keep-last: 10

### Cronjobs
cronjobs:
  - name: Restic Prune
    job: /usr/local/bin/runitor -uuid {{ secret_hc_mercy_purge }} -- /usr/local/bin/autorestic exec -a -- forget --keep-last 10 --prune
#    job: /usr/local/bin/runitor -uuid {{ secret_hc_mercy_purge }} -- /usr/local/bin/autorestic forget -a -- prune
    user: "{{ main_username }}"
    minute: 0
    hour: 21
    weekday: 1
  - name: Restic Check
    job: /usr/local/bin/runitor -uuid {{ secret_hc_restic_check_mercy }} -- /usr/local/bin/autorestic exec -a -- check
    user: "{{ main_username }}"
    minute: 30
    hour: 21
    day: 1
  - name: Restart BARbot
    job: /usr/local/bin/runitor -no-start-ping=true -uuid {{ secret_hc_mercy_bar }} -- systemctl restart bar.service
    user: root
    minute: 0
    hour: 3
  - name: Restart MATHBot
    job: /usr/local/bin/runitor -no-start-ping=true -uuid {{ secret_hc_mercy_math }} -- systemctl restart math.service
    user: root
    minute: 1
    hour: 3
  - name: Restart PhantomBot
    job: /usr/local/bin/runitor -no-start-ping=true -uuid {{ secret_hc_mercy_phantom }} -- systemctl restart phantom.service
    user: root
    minute: 2
    hour: 3
  - name: Restart TG Sync
    job: /usr/local/bin/runitor -no-start-ping=true -uuid {{ secret_hc_mercy_tg }} -- systemctl restart tg-sync.service
    user: root
    minute: 3
    hour: 3
  - name: Backup Media
    job: /usr/local/bin/runitor -uuid {{ secret_hc_mercy_media }} -- /usr/local/bin/autorestic backup -a -c /home/{{ main_username }}/.autorestic.yml
    user: root
    minute: 59
    hour: 2
