---
target_os: ubuntu
hostname: odium

### Variables
# nag_force_install: true
# nag_version: 0.0.7

### Install packages with grog.package
package_list:
  - name: curl
  - name: git
  - name: htop
  - name: wget
  - name: ethtool
  - name: ifupdown2

### Cronjobs
cronjobs:
  - name: Daily Suspend
    job: /usr/bin/systemctl suspend
    user: root
    minute: 0
    hour: 0

### Docker-Compose with ironicbadger.docker_compose_generator
appdata_path: /home/{{main_username}}/docker
containers:
  ###
  - service_name: matrix
    container_name: matrix
    active: false
    image: matrixdotorg/synapse:latest
    restart: always
    ports:
      - 5108:8008
      - 5448:8448
    volumes:
      - "{{ appdata_path }}/matrix/config:/data/"
    environment:
      - SYNAPSE_LOG_LEVEL=INFO
    depends_on:
      - matrix_db
    include_global_env_vars: false
  ###
  - service_name: matrix_db
    container_name: matrix_db
    active: false
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "{{ appdata_path }}/postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=matrix
      - POSTGRES_PASSWORD={{ secret_matrix_db_pass }}
    depends_on:
      - matrix_db
    include_global_env_vars: false
  ###
  - service_name: portainer_agent
    container_name: portainer_agent
    active: true
    image: portainer/agent
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    environment:
      - AGENT_SECRET={{secret_portainer_key}}
    labels:
      - "diun.enable=true"
      - "diun.regopt=docker.io"
    include_global_env_vars: false
