---
target_os: ubuntu
hostname: valor

### Install packages with grog.package
package_list:
  - name: curl
  - name: htop
  - name: net-tools
  - name: sudo
  - name: wget

### Pip Packages
pip_packages:
  - thefuck

### Bash Aliases

bash_docker: true
bash_systemctl: true
bash_apt: true

appdata_path: "/home/{{ main_username }}/docker"
containers:
  ###
  - service_name: adguard
    container_name: adguard
    active: true
    image: adguard/adguardhome:v0.107.9
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "81:80/tcp"
      - "444:443/tcp"
      - "3000:3000/tcp"
    volumes:
      - "{{ appdata_path }}/adguard/conf:/opt/adguardhome/conf"
      - "{{ appdata_path }}/adguard/work:/opt/adguardhome/work"
    cap_add:
      - NET_ADMIN
    include_global_env_vars: false
