---
### Variables
pull_backup: false

### Autorestic Config
autorestic_config_yaml:
  version: 2
  backends:
    synology_docker:
      type: rest
      path: 'http://192.168.30.25:8500/vasher'
      key: "{{ secret_restic_repo_password }}"
      rest:
        user: "{{ secret_restic_rest_user }}"
        password: "{{ secret_restic_rest_password }}"
  locations:
    docker:
      from: /home/{{ main_username }}
      to:
        - synology_docker
      options:
        backup:
          exclude:
            - '.cache*'
            - 'Nextcloud'
            - 'Downloads'
            - 'git'
            - '*steam*'
        forget:
          keep-daily: 3
          keep-weekly: 4
          keep-monthly: 2

desktop_hc_prune_id: "{{ secret_hc_restic_prune_vasher }}"
desktop_hc_backup_id: "{{ secret_hc_restic_backup_vasher }}"

### Telegraf
telegraf_influx_token: "{{ secret_telegraf_vasher }}"
telegraf_influx_bucket: vasher
telegraf_influx_disk_mounts: '"/"'