---

- name: create directories
  file:
    path: "/home/{{ main_username }}/{{ item }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  loop:
    - docker
    - scripts

- name: Copy scripts
  copy:
    src: "{{ item.path }}"
    dest: /home/{{ main_username }}/scripts/{{ item.path }}
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: "{{ item.mode }}"
  loop:
    - {path: "nextcloud_cron.sh", mode: "+x"}

- name: Copy photos script templates
  template:
    src: "{{ item.src }}"
    dest: /home/{{ main_username }}/scripts/{{ item.dest }}
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
  loop:
    - {src: 'photos.sh.j2', dest: 'photos.sh'}

#### Mount disks
- name: Set up disks/mounts
  include_tasks: disks.yml

#### FTP (scanner -> paperless consume)
- name: Set up FTP server
  include_tasks:
    file: ftp.yml
    apply:
      tags: ftp
  tags: ftp

### Backup Restore
- name: Create restore script
  copy:
    dest: /home/{{ main_username }}/restore.sh
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
    content: |
      #!/bin/bash
      /usr/local/bin/autorestic restore -f -l docker --from local_docker --to /
  when: pull_backup == true
- name: Run restore script
  command: /bin/bash ./restore.sh
  args:
    chdir: "/home/{{ main_username }}"
  when: pull_backup == true
- name: Remove restore script
  file:
    path: /home/{{ main_username }}/restore.sh
    state: absent
  when: pull_backup == true
