---

apt_dependencies:
  - gnupg2
  - gnupg-agent
  - apt-transport-https
  - python3-apt

apt_deb: deb https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release | lower }} main
apt_signkey: https://pkgs.tailscale.com/stable/ubuntu/{{ ansible_distribution_release | lower }}.noarmor.gpg

tailscale_package: tailscale
