services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1.12
    container_name: opengist
    volumes:
      - "{{ appdata_path }}/opengist:/opengist"
    ports:
      - 127.0.0.1:6157:6157
    environment:
      - OG_OIDC_PROVIDER_NAME=PocketID
      - OG_OIDC_CLIENT_KEY={{ secret_opengist_pocket_id_user }}
      - OG_OIDC_SECRET={{ secret_opengist_pocket_id_key }}
      - OG_OIDC_DISCOVERY_URL=https://id.{{ secret_personal_url }}/.well-known/openid-configuration
      - OG_OIDC_GROUP_CLAIM_NAME=opengist
      - OG_OIDC_ADMIN_GROUP=opengist-admins
    networks:
      - opengist-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  opengist-net:
