services:
  trilium:
    image: triliumnext/trilium:v0.102.2
    container_name: trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - TRILIUM_OAUTH_BASE_URL=https://notes.{{ secret_personal_internal_url }}
      - TRILIUM_OAUTH_CLIENT_ID={{ secret_trilium_pocket_id_user }}
      - TRILIUM_OAUTH_CLIENT_SECRET={{ secret_trilium_pocket_id_key }}
      - TRILIUM_OAUTH_ISSUER_BASE_URL=https://id.{{ secret_personal_url }}
      - TRILIUM_OAUTH_ISSUER_NAME=PocketID
      - TRILIUM_OAUTH_ISSUER_ICON=https://github.com/pocket-id/website/blob/main/static/img/logo.png?raw=true
    ports:
      - 8015:8080
    volumes:
      - "{{ appdata_path }}/trilium:/home/node/trilium-data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - trilium-net
    security_opt:
      - no-new-privileges:true

networks:
  trilium-net:
