---
kind: pipeline
type: docker
name: default

steps:
  - name: ansible-lint
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    commands:
      - pip3 install yamllint
      - "ansible-lint ."
      - "yamllint ."