---
kind: pipeline
type: docker
name: default

steps:
  - name: ansible-lint
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    commands:
      - pip3 install yamllint
#      - "find . -maxdepth 1 -name '*.yml' | sort | grep -v '.drone.yml' | xargs ansible-lint"
      - "yamllint ."