---
kind: pipeline
type: docker
name: default

steps:
  - name: ansible-lint
    image: python:3.8-slim-bullseye
    commands:
      - pip3 install "ansible-lint[yamllint]"
      - "ansible-lint ."
      - "yamllint ."