---
kind: pipeline
type: docker
name: Infra Checks

steps:
  - name: ansible-lint + yamllint
    image: fuzzymistborn/docker-linting:latest
    environment:
      VAULT_PW:
        from_secret: ansible_vault_password
    commands:
      - ansible-galaxy role install -r requirements.yaml
      - ansible-galaxy collection install -r requirements.yaml
      - "ansible-lint ."
      - "yamllint ."
      - echo $VAULT_PW > .vault-password
      - "find . -maxdepth 1 -name '*.yml' | sort | grep -v '.drone.yml' | xargs ansible-playbook --syntax-check --list-tasks --vault-password-file .vault-password"

  - name: Send TG Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: html
      message: >
        {{#success build.status}}
          \u2714\ufe0f Build for <b>{{repo.name}}</b> was <b>successful</b>.  Check output <a href= '{{build.link}}'>here</a>!
        {{else}}
          \u274c Build for <b>{{repo.name}}</b> has <b>FAILED</b>!  Check status <a href= '{{build.link}}'>here</a>!
        {{/success}}
    when:
      status: [ success, failure ]
