---
kind: pipeline
type: docker
name: Infra Checks

steps:
  - name: ansible-lint + yamllint
    image: fuzzymistborn/docker-linting:latest
    environment:
      VAULT_PW:
        from_secret: ansible_vault_password
    commands:
      - ansible-galaxy role install -r requirements.yaml
      - ansible-galaxy collection install -r requirements.yaml
      - "ansible-lint ."
      - "yamllint ."
      - echo $VAULT_PW > .vault-password
      - "find . -maxdepth 1 -name '*.yml' | sort | grep -v '.drone.yml' | xargs ansible-playbook --syntax-check --list-tasks --vault-password-file .vault-password"

  - name: Send TG Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: >
        {{#success build.status}}
          Build for *{{repo.name}}* was *successful*.  Check output [{{build.link}}](here)
        {{else}}
          *WARNING*: Build for *{{repo.name}}* has *FAILED*!  Check status [{{build.link}}](here)
        {{/success}}
    when:
      status: [ success, failure ]
