---
kind: pipeline
type: docker
name: default

steps:
  - name: ansible-lint
    image: ubuntu:20.04
    commands:
      - pip3 install "ansible-lint[community,yamllint]"
      - "ansibl-lint ."
      - "yamllint ."