steps:
  - name: ansible-lint and yamllint
    image: fuzzymistborn/docker-linting:latest
    environment:
      ansible_vault_password:
        from_secret: my_token
    commands:
      - ansible-galaxy role install -r requirements.yaml
      - ansible-galaxy collection install -r requirements.yaml
      - sed -i '8d' ansible.cfg
      - echo $ansible_vault_password > .vault-password
      - ansible-lint .
      - yamllint .
      - find . -maxdepth 1 -name '*.yml' | grep -v '.woodpecker.yml' | grep -v 'FUNDING.yml' | xargs ansible-playbook --syntax-check --list-tasks --vault-password-file .vault-password
    when:
      - event: push

  - name: Send TG Notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to:
        from_secret: tg_id
      format: markdown
      message: "{{#success build.status}}✅  Build for `{{repo.name}}` was *successful*!{{else}}❌  Build for `{{repo.name}}` has *FAILED*!{{/success}} \n🌐  [Output]({{build.link}})\n👤 Author: {{ commit.author }}\n📝  Commit: {{ commit.message }}"
    when:
      event: push 
      status:
        - success
        - failure