---

- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: target_hosts
      prompt: Which hosts to update? (space-separated, or 'all' for all docker hosts)
      private: no
      default: "all"

  tasks:
    - name: Get changed images from git
      shell: |
        cd {{ playbook_dir }}
        git diff HEAD@{1} HEAD -- services/*/compose.yaml services/*/compose.yml 2>/dev/null | \
        grep -E '^\+.*image:' | \
        sed 's/^+.*image: //' | \
        sed 's/\"//g' | \
        awk -F: '{print $1}' | \
        sort -u
      register: changed_images
      changed_when: false
      failed_when: false

    - name: Show changed images
      debug:
        msg: "Changed images: {{ changed_images.stdout_lines }}"
      when: changed_images.stdout_lines | length > 0

    - name: Exit if no changes
      meta: end_play
      when: changed_images.stdout_lines | length == 0

    - name: Get list of hosts to check
      set_fact:
        hosts_to_check: "{{ target_hosts.split() if target_hosts != 'all' else ['adonalsium', 'endowment', 'autonomy', 'cultivation', 'preservation', 'omada', 'honor', 'unity', 'ambition', 'investiture', 'invention', 'identity', 'virtuosity', 'whimsy'] }}"

    - name: Find affected containers per host
      shell: |
        cd {{ playbook_dir }}
        HOST="{{ item }}"

        # Find compose file
        compose_file="services/$HOST/compose.yaml"
        if [ ! -f "$compose_file" ]; then
          compose_file="services/$HOST/compose.yml"
        fi

        if [ ! -f "$compose_file" ]; then
          exit 0
        fi

        containers=""
        {% for image in changed_images.stdout_lines %}
        # Find services using this image
        service_names=$(awk -v img="{{ image }}" '
          /^  [a-z0-9_-]+:$/ {
            service = $1
            gsub(/:/, "", service)
          }
          /^    image:/ {
            if ($0 ~ img) {
              print service
            }
          }
        ' "$compose_file")

        if [ -n "$service_names" ]; then
          containers="$containers $service_names"
        fi
        {% endfor %}

        # Remove duplicates
        echo "$containers" | tr ' ' '\n' | grep -v '^$' | sort -u | tr '\n' ' ' | sed 's/ $//'
      register: host_containers
      loop: "{{ hosts_to_check }}"
      changed_when: false
      no_log: true

    - name: Build update plan
      set_fact:
        update_plan: "{{ update_plan | default([]) + [{'host': item.item, 'containers': item.stdout | trim}] }}"
      loop: "{{ host_containers.results }}"
      when: item.stdout | trim | length > 0
      no_log: true

    - name: Display update plan
      debug:
        msg: |

          ═══════════════════════════════════════════
               DOCKER UPDATE PLAN
          ═══════════════════════════════════════════
          {% if update_plan is defined and update_plan | length > 0 %}
          {% for plan in update_plan %}
          {{ "%-20s" | format(plan.host + ":") }} {{ plan.containers }}
          {% endfor %}
          {% else %}
          No containers need updating
          {% endif %}
          ═══════════════════════════════════════════

    - name: Confirm before proceeding
      pause:
        prompt: "Press ENTER to proceed with updates, or Ctrl+C to abort"
      when: update_plan is defined and update_plan | length > 0

    - name: Save update plan to temp file
      copy:
        content: "{{ update_plan | to_nice_json }}"
        dest: /tmp/ansible_docker_update_plan.json
      when: update_plan is defined and update_plan | length > 0

- hosts: docker
  become: true
  vars_files:
    - 'vars/vault.yaml'
  gather_facts: false
  ignore_unreachable: true

  tasks:
    - name: Check connectivity
      ping:
      register: connectivity_check
      ignore_errors: true
      ignore_unreachable: true

    - name: Load update plan
      delegate_to: localhost
      become: false
      slurp:
        path: /tmp/ansible_docker_update_plan.json
      register: update_plan_file
      run_once: true
      when: connectivity_check is succeeded

    - name: Parse update plan
      set_fact:
        update_plan: "{{ update_plan_file.content | b64decode | from_json }}"
      run_once: true
      when: connectivity_check is succeeded

    - name: Get actual hostname from inventory
      set_fact:
        actual_hostname: "{{ group_names | reject('search', 'children') | reject('in', ['docker', 'lxc', 'vms', 'desktop', 'ubuntu', 'fedora', 'shards']) | first }}"
      when: connectivity_check is succeeded

    - name: Find containers for this host
      set_fact:
        my_containers: "{{ (update_plan | selectattr('host', 'equalto', actual_hostname) | first).containers | default('') }}"
      when: connectivity_check is succeeded

    - name: Show what will be updated on this host
      debug:
        msg: "{{ actual_hostname }}: {{ my_containers if my_containers else 'Nothing to update' }}"
      when: connectivity_check is succeeded

    - name: Docker Pull
      command: "docker compose pull {{ my_containers }}"
      args:
        chdir: /home/{{ main_username }}/
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0
      register: pull_result

    - name: Docker Update
      command: "docker compose up -d {{ my_containers }}"
      args:
        chdir: /home/{{ main_username }}/
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0
      register: update_result

    - name: Show pull output
      debug:
        var: pull_result.stdout_lines
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0
        - pull_result is defined

    - name: Docker prune
      command: "docker image prune -af"
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0

    - name: Collect update results for successful hosts
      set_fact:
        update_summary: "{{ update_summary | default([]) + [{'host': actual_hostname, 'containers': my_containers, 'updated': update_result.changed | default(false), 'status': 'success'}] }}"
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0
      delegate_to: localhost
      delegate_facts: true
      run_once: false

    - name: Record unreachable hosts
      set_fact:
        update_summary: "{{ update_summary | default([]) + [{'host': actual_hostname | default(inventory_hostname), 'containers': 'N/A', 'updated': false, 'status': 'unreachable'}] }}"
      when: connectivity_check is failed or connectivity_check is unreachable
      delegate_to: localhost
      delegate_facts: true
      run_once: false
      ignore_errors: true

    - name: Clear host errors to continue playbook
      meta: clear_host_errors

  roles:
    - role: docker-compose-generator
      when: connectivity_check is succeeded

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Display final summary
      debug:
        msg: |

          ═══════════════════════════════════════════
               UPDATE SUMMARY
          ═══════════════════════════════════════════
          {% if update_summary is defined and update_summary | length > 0 %}
          {% for result in update_summary %}
          {% if result.status == 'unreachable' %}
          {{ "%-20s" | format(result.host + ":") }} OFFLINE (skipped)
          {% else %}
          {{ "%-20s" | format(result.host + ":") }} {{ result.containers }} {{ "✓" if result.updated else "→" }}
          {% endif %}
          {% endfor %}
          {% else %}
          No containers were updated
          {% endif %}
          ═══════════════════════════════════════════
      when: update_summary is defined

    - name: Cleanup temp file
      file:
        path: /tmp/ansible_docker_update_plan.json
        state: absent