---

- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: target_hosts
      prompt: Which hosts to update? (space-separated, or 'all' for all docker hosts)
      private: no
      default: "all"

  tasks:
    - name: Get changed images from git
      shell: |
        cd {{ playbook_dir }}
        git diff HEAD@{1} HEAD -- services/*/compose.yaml services/*/compose.yml 2>/dev/null | \
        grep -E '^\+.*image:' | \
        sed 's/^+.*image: //' | \
        sed 's/\"//g' | \
        awk -F: '{print $1}' | \
        sort -u
      register: changed_images
      changed_when: false
      failed_when: false

    - name: Show changed images
      debug:
        msg: "Changed images: {{ changed_images.stdout_lines }}"
      when: changed_images.stdout_lines | length > 0

    - name: Exit if no changes
      meta: end_play
      when: changed_images.stdout_lines | length == 0

    - name: Get list of all docker hosts from inventory
      set_fact:
        all_docker_hosts: "{{ groups['docker'] | map('extract', hostvars, 'group_names') | map('reject', 'search', 'children') | map('reject', 'in', ['docker', 'lxc', 'vms', 'desktop', 'ubuntu', 'fedora', 'arch', 'shards']) | map('first') | unique | list }}"

    - name: Get list of hosts to check
      set_fact:
        hosts_to_check: "{{ target_hosts.split() if target_hosts != 'all' else all_docker_hosts }}"

    - name: Find affected containers per host
      shell: |
        cd {{ playbook_dir }}
        HOST="{{ item }}"

        # Find compose file
        compose_file="services/$HOST/compose.yaml"
        if [ ! -f "$compose_file" ]; then
          compose_file="services/$HOST/compose.yml"
        fi

        if [ ! -f "$compose_file" ]; then
          exit 0
        fi

        containers=""
        {% for image in changed_images.stdout_lines %}
        # Find services using this image
        service_names=$(awk -v img="{{ image }}" '
          /^  [a-z0-9_-]+:$/ {
            service = $1
            gsub(/:/, "", service)
          }
          /^    image:/ {
            if ($0 ~ img) {
              print service
            }
          }
        ' "$compose_file")

        if [ -n "$service_names" ]; then
          containers="$containers $service_names"
        fi
        {% endfor %}

        # Remove duplicates
        echo "$containers" | tr ' ' '\n' | grep -v '^$' | sort -u | tr '\n' ' ' | sed 's/ $//'
      register: host_containers
      loop: "{{ hosts_to_check }}"
      changed_when: false
      no_log: true

    - name: Build update plan
      set_fact:
        update_plan: "{{ update_plan | default([]) + [{'host': item.item, 'containers': item.stdout | trim}] }}"
      loop: "{{ host_containers.results }}"
      when: item.stdout | trim | length > 0
      no_log: true

    - name: Sort update plan alphabetically
      set_fact:
        update_plan: "{{ update_plan | sort(attribute='host') }}"
      when: update_plan is defined and update_plan | length > 0

    - name: Build update plan display
      set_fact:
        plan_header:
          - ""
          - "═══════════════════════════════════════════════════════════"
          - "            DOCKER UPDATE PLAN"
          - "═══════════════════════════════════════════════════════════"
        plan_lines: "{{ plan_lines | default([]) + [('  %-20s' | format(item.host + ':')) + item.containers] }}"
      loop: "{{ update_plan | default([]) }}"
      when: update_plan is defined and update_plan | length > 0

    - name: Display update plan
      debug:
        msg: "{{ plan_header + plan_lines + ['═══════════════════════════════════════════════════════════'] }}"
      when: update_plan is defined and update_plan | length > 0

    - name: No updates needed
      debug:
        msg:
          - ""
          - "═══════════════════════════════════════════════════════════"
          - "No containers need updating"
          - "═══════════════════════════════════════════════════════════"
      when: update_plan is not defined or update_plan | length == 0

    - name: Confirm before proceeding
      pause:
        prompt: "Press ENTER to proceed with updates, or Ctrl+C to abort"
      when: update_plan is defined and update_plan | length > 0

    - name: Save update plan to temp file
      copy:
        content: "{{ update_plan | to_nice_json }}"
        dest: /tmp/ansible_docker_update_plan.json
      when: update_plan is defined and update_plan | length > 0

- hosts: docker
  become: true
  vars_files:
    - 'vars/vault.yaml'
  gather_facts: false
  ignore_unreachable: true

  roles:
    - role: docker-compose-generator

  tasks:
    - name: Check connectivity
      ping:
      register: connectivity_check
      ignore_errors: true
      ignore_unreachable: true

    - name: Load update plan
      delegate_to: localhost
      become: false
      slurp:
        path: /tmp/ansible_docker_update_plan.json
      register: update_plan_file
      run_once: true
      when: connectivity_check is succeeded

    - name: Parse update plan
      set_fact:
        update_plan: "{{ update_plan_file.content | b64decode | from_json }}"
      run_once: true
      when: connectivity_check is succeeded

    - name: Get actual hostname from inventory
      set_fact:
        actual_hostname: "{{ group_names | reject('search', 'children') | reject('in', ['docker', 'lxc', 'vms', 'desktop', 'ubuntu', 'fedora', 'shards']) | first }}"
      when: connectivity_check is succeeded

    - name: Find containers for this host
      set_fact:
        my_containers: "{{ (update_plan | selectattr('host', 'equalto', actual_hostname) | first).containers | default('') }}"
      when: connectivity_check is succeeded

    - name: Show what will be updated on this host
      debug:
        msg: "{{ actual_hostname }}: {{ my_containers if my_containers else 'Nothing to update' }}"
      when: connectivity_check is succeeded

    - name: Docker Pull
      command: "docker compose pull {{ my_containers }}"
      args:
        chdir: /home/{{ main_username }}/
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0
      register: pull_result

    - name: Docker Update
      command: "docker compose up -d {{ my_containers }}"
      args:
        chdir: /home/{{ main_username }}/
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0
      register: update_result

    - name: Show pull output
      debug:
        var: pull_result.stdout_lines
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0
        - pull_result is defined

    - name: Docker prune
      command: "docker image prune -af"
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0

    - name: Collect update results for successful hosts
      set_fact:
        my_update_result:
          host: "{{ actual_hostname }}"
          containers: "{{ my_containers }}"
          updated: "{{ update_result.changed | default(false) }}"
          status: "success"
      when:
        - connectivity_check is succeeded
        - my_containers | length > 0

    - name: Collect unreachable host info
      set_fact:
        my_update_result:
          host: "{{ actual_hostname | default(inventory_hostname) }}"
          containers: "N/A"
          updated: false
          status: "unreachable"
      when: connectivity_check is failed or connectivity_check is unreachable
      ignore_errors: true

    - name: Send results to localhost
      delegate_to: localhost
      delegate_facts: true
      set_fact:
        all_results: "{{ all_results | default([]) + [hostvars[item]['my_update_result']] }}"
      loop: "{{ ansible_play_hosts_all }}"
      run_once: true
      when: hostvars[item].my_update_result is defined

    - name: Clear host errors to continue playbook
      meta: clear_host_errors

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Sort summary alphabetically
      set_fact:
        update_summary: "{{ all_results | sort(attribute='host') }}"
      when: all_results is defined and all_results | length > 0

    - name: Build summary display
      set_fact:
        summary_header:
          - ""
          - "═══════════════════════════════════════════════════════════"
          - "            UPDATE SUMMARY"
          - "═══════════════════════════════════════════════════════════"
        summary_lines: "{{ summary_lines | default([]) + [('  %-20s' | format(item.host + ':')) + (item.containers if item.status != 'unreachable' else 'OFFLINE (skipped)') + (' ✓' if item.updated else '')] }}"
      loop: "{{ update_summary | default([]) }}"
      when: update_summary is defined and update_summary | length > 0

    - name: Display final summary
      debug:
        msg: "{{ summary_header + summary_lines + ['═══════════════════════════════════════════════════════════'] }}"
      when: update_summary is defined and update_summary | length > 0

    - name: No updates message
      debug:
        msg:
          - ""
          - "═══════════════════════════════════════════════════════════"
          - "No containers were updated"
          - "═══════════════════════════════════════════════════════════"
      when: update_summary is not defined or update_summary | length == 0

    - name: Cleanup temp file
      file:
        path: /tmp/ansible_docker_update_plan.json
        state: absent