---
roles:
- src: IronicBadger.ansible_role_docker_compose_generator
- src: IronicBadger.ansible_role_snapraid
- src: caddy_ansible.caddy_ansible
- src: grog.package
- src: geerlingguy.docker
- src: geerlingguy.ntp
- src: geerlingguy.nfs
- src: geerlingguy.pip
- src: geerlingguy.samba
- src: fuzzymistborn.autorestic

collections:
- community.docker
- ansible.posix
- kewlfft.aur
