---
roles:
- src: ironicbadger.snapraid
- src: caddy_ansible.caddy_ansible
- src: grog.package
- src: geerlingguy.docker
- src: geerlingguy.ntp
- src: geerlingguy.nfs
- src: geerlingguy.pip
- src: geerlingguy.samba
- src: fuzzymistborn.autorestic

collections:
- community.docker
- ansible.posix
