roles:
- src: ironicbadger.ansible_role_docker_compose_generator
- src: ironicbadger.ansible_role_snapraid
- src: grog.package
- src: geerlingguy.docker
- src: geerlingguy.ntp
- src: geerlingguy.nfs
- src: geerlingguy.pip
- src: geerlingguy.samba

collections:
- community.general
- community.docker