---
roles:
- src: ironicbadger.docker_compose_generator
- src: ironicbadger.snapraid
- src: caddy_ansible.caddy_ansible
- src: grog.package
- src: geerlingguy.docker
- src: geerlingguy.ntp
- src: geerlingguy.nfs
- src: geerlingguy.pip
  version: 2.2.0
- src: geerlingguy.samba
- src: fuzzymistborn.autorestic

collections:
- community.docker
- ansible.posix
- kewlfft.aur
