---
- hosts: all
  become: true
  tasks:
# Ubuntu
    - name: Set timezone
      timezone:
        name: "{{ ntp_timezone }}"
      when: ansible_distribution == 'Ubuntu'
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
        - 88-esm-announce
        - 91-contract-ua-esm-status
      when: ansible_distribution == 'Ubuntu'
    - name: Remove Ubuntu Snap
      apt:
        name: snapd
        state: absent
        purge: true
      when: ansible_distribution == 'Ubuntu'
# Fedora
    - name: Install the rpmfusion and fonts repo packages
      dnf:
        state: present
        disable_gpg_check: yes
        name:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_version }}.noarch.rpm
      become: yes
      when: ansible_distribution == 'Fedora'
    - name: Improve DNF Performances
      blockinfile:
        path: /etc/dnf/dnf.conf
        create: yes
        block: |
          [main]
          gpgcheck=1
          installonly_limit=3
          clean_requirements_on_remove=True
          best=False
          skip_if_unavailable=True
          fastestmirror=1
          max_parallel_downloads=10
          deltarpm=true
      become: yes
      when: ansible_distribution == 'Fedora'
    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == 'Fedora'

- hosts: adonalsium
  become: true
  vars_files:
    - 'vars/vault.yaml'
  pre_tasks:
    - name: Remove enterprise repo
      file:
        state: absent
        path: /etc/apt/sources.list.d/pve-enterprise.list
    - name: Switch to community repo
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
        state: present
    - name: Apt update
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - role: install/nag_removal
    - role: grog.package
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: geerlingguy.samba
    - role: geerlingguy.nfs
    - role: install/mergerfs
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: install/zsh
    - role: adonalsium
    - role: bash_alias
    - role: cronjobs
    - role: geerlingguy.docker
    - role: geerlingguy.ntp
    - role: install/lnxlink
    - role: ironicbadger.docker_compose_generator
    - role: ironicbadger.snapraid

- hosts: ishap
  become: true
  vars_files:
    - 'vars/vault.yaml'
  pre_tasks:
    - name: Remove enterprise repo
      file:
        state: absent
        path: /etc/apt/sources.list.d/pve-enterprise.list
    - name: Switch to community repo
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
        state: present
    - name: Apt update
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - role: install/nag_removal
    - role: grog.package
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: geerlingguy.nfs
    - role: install/mergerfs
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: install/zsh
    - role: ishap
    - role: bash_alias
    - role: cronjobs
    - role: geerlingguy.docker
    - role: geerlingguy.ntp
    - role: ironicbadger.docker_compose_generator
    - role: ironicbadger.snapraid

### LXCs/VMs/VPS
- hosts: dominion
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: github
    - role: install/bitwarden_cli
    - role: install/runitor
    - role: install/zsh
    - role: dominion
    - role: bash_alias
    - role: cronjobs

- hosts: endowment
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.samba
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: fuzzymistborn.autorestic
    - role: install/lnxlink
    - role: install/runitor
    - role: install/zsh
    - role: endowment
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: autonomy
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: github
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: install/zsh
    - role: autonomy
    - role: bash_alias
    - role: cronjobs
    - role: install/lnxlink
    - role: ironicbadger.docker_compose_generator

- hosts: unity
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: install/zsh
    - role: unity
    - role: bash_alias
    - role: install/tailscale
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: virtuosity
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: install/zsh
    - role: virtuosity
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: cultivation
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: fuzzymistborn.autorestic
    - role: install/lnxlink
    - role: install/runitor
    - role: install/zsh
    - role: cultivation
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: preservation
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: fuzzymistborn.autorestic
    - role: install/lnxlink
    - role: install/runitor
    - role: install/zsh
    - role: ironicbadger.docker_compose_generator
    - role: preservation
    - role: bash_alias
    - role: cronjobs

- hosts: honor
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: install/lego
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: caddy_ansible.caddy_ansible
    - role: install/zsh
    - role: honor
    - role: bash_alias
    - role: cronjobs
    - role: install/fail2ban
    - role: ironicbadger.docker_compose_generator

- hosts: omada
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: install/zsh
    - role: omada
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: invention
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: install/zsh
    - role: invention
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: bash_alias
    - role: ironicbadger.docker_compose_generator

- hosts: connection
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: install/zsh
    - role: connection
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: drone
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: install/runitor
    - role: install/zsh
    - role: bash_alias
    - role: ironicbadger.docker_compose_generator
    - role: cronjobs

- hosts: ambition
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: install/lego
    - role: install/tailscale
    - role: install/zsh
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: ironicbadger.docker_compose_generator
    - role: ambition
    - role: caddy_ansible.caddy_ansible
    - role: bash_alias
    - role: cronjobs
    - role: install/fail2ban

### Desktops
- hosts: vasher
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/desktop.yml'
    - 'group_vars/vasher.yml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: desktop
    - role: install/zsh
    - role: bash_alias

- hosts: szeth
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/desktop.yml'
    - 'group_vars/szeth.yml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: fuzzymistborn.autorestic
    - role: install/runitor
    - role: desktop
    - role: install/zsh
    - role: bash_alias

- hosts: design
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/design.yml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: design
    - role: bash_alias
    - role: install/zsh

- hosts: hoid
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/hoid.yml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install/pip_packages
    - role: desktop
    - role: install/zsh
    - role: bash_alias
