---
- hosts: all
  become: true
  tasks:
    - name: Set timezone
      timezone:
        name: "{{ ntp_timezone }}"
      when: ansible_distribution == 'Ubuntu'
    - name: Remove Ubuntu motd spam
      file:
        path: "/etc/update-motd.d/{{ item }}"
        state: absent
      loop:
        - 80-livepatch
        - 95-hwe-eol
        - 50-motd-news
        - 10-help-text
      when: ansible_distribution == 'Ubuntu'

- hosts: adonalsium
  become: true
  vars_files:
    - 'vars/vault.yaml'
  pre_tasks:
    - name: Remove enterprise repo
      file:
        state: absent
        path: /etc/apt/sources.list.d/pve-enterprise.list
    - name: Switch to community repo
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription'
        state: present
    - name: Apt update
      apt:
        upgrade: 'yes'
        update_cache: yes
        cache_valid_time: 3600
  roles:
    - role: install_nag_removal
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: geerlingguy.samba
    - role: geerlingguy.nfs
    - role: install_mergerfs
    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: install_telegraf
    - role: adonalsium
    - role: bash_alias
    - role: install_syncthing
    - role: cronjobs
    - role: geerlingguy.docker
    - role: geerlingguy.ntp
    - role: ironicbadger.docker_compose_generator
    - role: ironicbadger.snapraid

### LXCs/VMs/VPS
- hosts: dominion
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: github
    - role: install_bitwarden_cli
    - role: install_runitor
    - role: dominion
    - role: bash_alias
    - role: cronjobs

- hosts: endowment
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.samba
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: fuzzymistborn.autorestic
    - role: install_telegraf
    - role: install_runitor
    - role: endowment
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: autonomy
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: github
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: fuzzymistborn.autorestic
    - role: install_telegraf
    - role: install_runitor
    - role: autonomy
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: unity
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: install_pip_packages
#    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: unity
    - role: bash_alias
#    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: cultivation
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: fuzzymistborn.autorestic
    - role: install_telegraf
    - role: install_runitor
    - role: cultivation
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: preservation
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: fuzzymistborn.autorestic
    - role: install_telegraf
    - role: install_runitor
    - role: ironicbadger.docker_compose_generator
    - role: preservation
    - role: bash_alias
    - role: cronjobs

- hosts: honor
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: geerlingguy.docker
    - role: install_lego
    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: caddy_ansible.caddy_ansible
    - role: honor
    - role: bash_alias
    - role: cronjobs
    - role: install_fail2ban
    - role: ironicbadger.docker_compose_generator

- hosts: valor
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: geerlingguy.docker
    - role: valor
    - role: bash_alias
    - role: ironicbadger.docker_compose_generator

- hosts: omada
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: install_pip_packages
    - role: geerlingguy.docker
    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: omada
    - role: bash_alias
    - role: cronjobs
    - role: ironicbadger.docker_compose_generator

- hosts: drone
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: geerlingguy.docker
    - role: bash_alias
    - role: ironicbadger.docker_compose_generator

- hosts: ambition
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: geerlingguy.docker
    - role: install_lego
    - role: install_tailscale
    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: ironicbadger.docker_compose_generator
    - role: ambition
    - role: caddy_ansible.caddy_ansible
    - role: bash_alias
    - role: cronjobs
    - role: install_fail2ban

### Desktops

- hosts: kelsier
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/desktop.yml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: desktop
    - role: kelsier
    - role: bash_alias
    - role: config_retroarch
    - role: config_pegasus
    - role: install_syncthing
    - role: install_telegraf
    - role: cronjobs

- hosts: vasher
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/desktop.yml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
#    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: desktop
#    - role: vasher
    - role: bash_alias
#    - role: cronjobs

- hosts: mraize
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/desktop.yml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
#    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: desktop
#    - role: mraize
    - role: bash_alias
#    - role: cronjobs

- hosts: hoid
  become: true
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.pip
    - role: install_pip_packages
#    - role: fuzzymistborn.autorestic
    - role: install_runitor
    - role: desktop
#    - role: hoid
    - role: bash_alias
#    - role: cronjobs

- hosts: retroarch_tv
  become: true
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/desktop.yml'
  roles:
    - role: grog.package
    - role: desktop
    - role: retroarch_tv
    - role: config_retroarch
    - role: config_pegasus
    - role: bash_alias
    - role: cronjobs
    - role: install_syncthing
