---

- hosts: shards ambition
  tasks:
    - name: update all packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: 'yes'
        autoremove: yes

- hosts: adonalsium
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/all.yaml'
  roles:
    - role: install_mergerfs
      become: true
    - role: install_runitor
    - role: install_telegraf
      become: true
  tasks:
    - name: update all packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: dist
        autoremove: yes

- hosts: ambition
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/all.yaml'
  roles:
#    - role: install_hugo
    - role: install_lego
    - role: install_runitor

- hosts: honor
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/all.yaml'
  roles:
    - role: install_lego
    - role: install_runitor

- hosts: dominion omada kelsier
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/all.yaml'
  roles:
    - role: install_runitor

- hosts: endowment autonomy cultivation preservation
  vars_files:
    - 'vars/vault.yaml'
    - 'group_vars/all.yaml'
  roles:
    - role: install_runitor
    - role: install_telegraf
      become: true
