---

- hosts: shards ambition
  tasks:
    - name: update all packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: 'yes'
        autoremove: yes

- hosts: adonalsium
  tasks:
    - name: update all packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400
        upgrade: dist
        autoremove: yes
