---

- hosts: shards
  tasks:
    - name: update all packages
      become: true
      package:
        name: '*'
        state: latest

- hosts: adonalsium
  tasks:
    - name: update all packages
      become: true
      package:
        name: '*'
        state: latest

- hosts: docker
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: ironicbadger.ansible_role_docker_compose_generator