---
### SSH Config
- name: Fix SFTP for Ansible
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    state: present
    regexp: "Subsystem sftp*"
    line: "Subsystem sftp internal-sftp"

- name: Restart ssh
  service:
    name: sshd
    state: restarted

- name: create .ssh folder
  file:
    dest: /home/{{main_username}}/.ssh
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0660

- name: Add SSH Keys
  copy:
    dest: /home/{{ main_username }}/.ssh/{{ item.dest }}
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ item.key }}"
  loop:
    - dest: desktop_lxcs
      key: "{{ secret_desktop_lxc_ssh }}"
    - dest: desktop_ambition
      key: "{{ secret_desktop_ambition_ssh }}"
    - dest: github
      key: "{{ secret_github_ssh }}"

- name: Copy template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
  loop:
    - {src: "ssh_config.j2", dest: "/home/{{ main_username }}/.ssh/config", mode: "600"}

### Sudoers file
- name: Add sudoers file for main user
  template:
    src: sudoers_main_user.j2
    dest: /etc/sudoers.d/{{ main_username }}
    owner: root
    group: root
    mode: 0440

### Flatpak
- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install Flatpaks
  community.general.flatpak:
    name:
      - "{{ item.name }}"
    state: present
#    method: user
  loop: "{{ flatpak_list }}"

### fstab/disk mounts
- name: make sure disks unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  loop: "{{ mountpoints }}"
  when: ansible_hostname != 'hoid'

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: "{{ main_username }}"
    group: nobody
    mode: 0777
  loop: "{{ mountpoints }}"
  when: ansible_hostname != 'hoid'

- name: Add smbcredentials
  copy:
    dest: /home/{{ main_username }}/.smbcredentials
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: |
      user=samba
      password={{ secret_samba_pass }}
      domain=cosmere
  when: ansible_hostname != 'hoid'

- name: mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: present
  loop: "{{ mountpoints }}"
  when: ansible_hostname != 'hoid'

### ZSH
- name: Copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
  loop:
    - src: "zsh/zshrc"
      dest: "/home/{{ main_username }}/.zshrc"
    - src: "zsh/p10k.zsh"
      dest: "/home/{{ main_username }}/.p10k.zsh"

### Backup/Restore
- name: Create restore script
  copy:
    dest: /home/{{ main_username }}/restore.sh
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
    content: |
      #!/bin/bash
      /usr/local/bin/autorestic restore -f -l home --from synology_docker --to /
  when: pull_backup == true
- name: Run restore script
  command: /bin/bash ./restore.sh
  args:
    chdir: "/home/{{ main_username }}"
  when: pull_backup == true
- name: Remove restore script
  file:
    path: /home/{{ main_username }}/restore.sh
    state: absent
  when: pull_backup == true

### VS Code Extensions
- name: Install extensions
  command: code --install-extension {{ item }}
  become: yes
  become_user: "{{ main_username }}"
  loop:
    - ms-vscode-remote.remote-ssh
    - ms-python.python
    - ms-azuretools.vscode-docker
    - matthewpi.caddyfile-support
    - keesschollaart.vscode-home-assistant
    - wholroyd.jinja

### CUPS
- name: Add printer and set as default
  command: "{{ item }}"
  become: yes
  become_user: "{{ main_username }}"
  loop:
    - /usr/sbin/lpadmin -p Brother-HL2270DW -E -v ipp://192.168.10.15/ipp/port1 -o media=na_letter_8.5x11in
    - /usr/bin/lpoptions -d Brother-HL2270DW

### Final Tweaks
- name: create mpv config folder
  file:
    dest: /home/{{main_username}}/.config/mpv
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0660

- name: Install plugin for MPV to use KDEConnect
  get_url:
    url: https://github.com/hoyon/mpv-mpris/releases/download/1.1/mpris.so
    dest: /home/{{ main_username }}/.config/mpv/scripts
    force: yes
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

- name: Enable WOL
  command: nmcli c modify "Wired connection 1" 802-3-ethernet.wake-on-lan magic

- name: Copy Personal avatar
  copy:
    src: face
    dest: /home/{{ main_username }}/.face
    mode: 0644
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

- name: Copy login screen image
  copy:
    src: WayofKings.jpg
    dest: /usr/share/backgrounds/WayofKings.jpg
    mode: 0644
    owner: root
    group: root

- name: enable bluetooth auto-power on
  lineinfile:
    dest: "/etc/bluetooth/main.conf"
    state: present
    regexp: "^AutoEnable"
    line: "AutoEnable=true"
  when: ansible_hostname != 'hoid'

### Restic
- name: Copy systemd service file
  template:
    src: ../templates//systemd/{{ item }}.j2
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - restic_backup.service
    - restic_backup.timer
    - restic_prune.service
    - restic_prune.timer
  when: ansible_hostname != 'hoid'

- name: Reload systemd services/timers
  systemd:
    enabled: true
    daemon-reload: true
    state: started
    name: "{{ item }}"
    no_block: true
  loop:
    - restic_backup.service
    - restic_backup.timer
    - restic_prune.service
    - restic_prune.timer
  when: ansible_hostname != 'hoid'

### Logiops
- name: Copy Szeth logid.cfg file
  copy:
    src: szeth_logid.cfg
    dest: /etc/logid.cfg
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == 'szeth'

- name: Reload/Enable Systemd processes
  systemd:
    enabled: true
    daemon-reload: true
    state: restarted
    name: "{{ item }}"
  loop:
    - logid
  when: ansible_hostname == 'szeth'
