services:
  zwavejs:
    image: ghcr.io/zwavejs/zwave-js-ui:9.30.1
    container_name: zwavejs
    devices:
      - /dev/zwave:/dev/zwave
    volumes:
      - "{{ appdata_path }}/zwavejs:/usr/src/app/store"
    ports:
      - 8091:8091
      - 3500:3000
    environment:
      - TZ={{ ntp_timezone }}
    restart: always
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.1.1
    container_name: zigbee2mqtt
    devices:
      - /dev/zigbee:/dev/zigbee
    volumes:
      - "{{ appdata_path }}/zigbee2mqtt:/app/data"
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ={{ ntp_timezone }}
    restart: always
  adguard:
    image: adguard/adguardhome:v0.107.56
    container_name: adguard
    cap_add:
      - NET_ADMIN
    volumes:
      - "{{ appdata_path }}/adguard/conf:/opt/adguardhome/conf"
      - "{{ appdata_path }}/adguard/work:/opt/adguardhome/work"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 81:80/tcp
      - 444:443/tcp
      - 3000:3000/tcp
    restart: always
  portainer_agent:
    image: portainer/agent:2.26.1
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    environment:
      - AGENT_SECRET={{ secret_portainer_key }}
    restart: always
  nut-ups:
    image: fuzzymistborn/nut-upsd:2.8.2
    container_name: nut-ups
    devices:
      - /dev/bus/usb/001/004:/dev/bus/usb/001/004
    ports:
      - 3493:3493
    environment:
      - API_USER=homeassistant
      - API_PASSWORD={{ secret_nut_api_pw }}
    restart: always
