services:
  zwavejs:
    image: ghcr.io/zwave-js/zwave-js-ui:11.1.0
    container_name: zwavejs
    devices:
      - /dev/zwave:/dev/zwave
    volumes:
      - "{{ appdata_path }}/zwavejs:/usr/src/app/store"
    ports:
      - 8091:8091
      - 3500:3000
    environment:
      - TZ={{ ntp_timezone }}
    restart: unless-stopped
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.6.0
    container_name: zigbee2mqtt
    devices:
      - /dev/zigbee:/dev/zigbee
    volumes:
      - "{{ appdata_path }}/zigbee2mqtt:/app/data"
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ={{ ntp_timezone }}
    restart: unless-stopped
  adguard:
    image: adguard/adguardhome:v0.107.64
    container_name: adguard
    cap_add:
      - NET_ADMIN
    volumes:
      - "{{ appdata_path }}/adguard/conf:/opt/adguardhome/conf"
      - "{{ appdata_path }}/adguard/work:/opt/adguardhome/work"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 81:80/tcp
      - 444:443/tcp
      - 3000:3000/tcp
    restart: unless-stopped
  portainer_agent:
    image: portainer/agent:2.32.0
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    environment:
      - AGENT_SECRET={{ secret_portainer_key }}
    restart: unless-stopped
  nut-ups:
    image: fuzzymistborn/nut-upsd:2.8.2
    container_name: nut-ups
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 3493:3493
    environment:
      - API_USER=homeassistant
      - API_PASSWORD={{ secret_nut_api_pw }}
    restart: unless-stopped
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS="north-america.pool.ntp.org,time.nist.gov,0.fedora.pool.ntp.org,0.debian.pool.ntp.org"
      - LOG_LEVEL=0 
      - TZ={{ ntp_timezone }}
