services:
  ollama-server:
    image: ollama/ollama:0.23.0
    container_name: ollama-server
    volumes:
      - /mnt/llms/ollama:/root/.ollama
    ports:
      - 11434:11434
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - ollama-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:unified-cuda
    container_name: llama-swap
    volumes:
      - /mnt/llms/models:/models:ro
      - "{{ appdata_path }}llama/config.yml:/app/config.yml:ro
    ports:
      - 8080:8080
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - llama-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.9.2
    container_name: open-webui
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "{{ appdata_path }}/ollama-webui:/app/backend/data"
    ports:
      - 3010:8080
    environment:
      - WEBUI_SECRET_KEY={{ secret_webui_secret_key }}
      - OPENAI_API_BASE_URL=http://llama-swap:8080/v1
      - OPENAI_API_KEY=none
    networks:
      - llama-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  ollama-net:
  llama-net:
