services:
  gluetun:
    image: qmcgaw/gluetun:v3.41.1
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - "{{ appdata_path }}/gluetun:/gluetun"
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY={{ secret_mullvad_key }}
      - WIREGUARD_ADDRESSES={{ secret_mullvad_url }}
      - SERVER_CITIES={{ secret_mullvad_cities }}
      - DNS_ADDRESS=192.168.1.11
      - TZ={{ ntp_timezone }}
      - UPDATER_PERIOD=24h
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  tailscale:
    image: ghcr.io/tailscale/tailscale:v1.96.5
    container_name: tailscale
#    network_mode: service:gluetun
    privileged: true
    cap_add:
      - net_admin
      - sys_module
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - "{{ appdata_path }}/tailscale:/var/lib/tailscale"
    environment:
      - TS_HOSTNAME=ishap
#      - TS_AUTHKEY={{ secret_ishap_tailscale_key }}
      - TS_EXTRA_ARGS= --advertise-exit-node --accept-routes
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
    restart: unless-stopped
