listen=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022
chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/mnt/Media/Files/scans
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40100
pasv_address=192.168.1.10
