---

- name: get latest release
  uri:
    url: https://api.github.com/repos/gohugoio/hugo/releases/latest
    return_content: true
  register: release_latest
  when: hugo_ver is undefined

- name: set version if not already
  set_fact: hugo_ver="{{ release_latest.json.tag_name }}"
  when: hugo_ver is undefined

- name: download release
  unarchive:
    src: https://github.com/gohugoio/hugo/releases/download/{{hugo_ver}}/hugo_{{hugo_ver | regex_replace('v')}}_Linux-64bit.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    owner: "{{main_username}}"
    group: "{{main_username}}"
    mode: +x

- name: remove unneeded files
  file:
    path: /usr/local/bin/{{item}}
    state: absent
  with_items:
    - LICENSE
    - README.md