services:
  selenium:
    image: selenium/standalone-firefox:149.0
    container_name: selenium
    ports:
      - 4444:4444
    environment:
      - SE_NODE_MAX_SESSIONS=2
      - TZ={{ ntp_timezone }}
    shm_size: 2g
    networks:
      - selenium-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  selenium-net:
