services:
  dockhand:
    image: fnsys/dockhand:v1.0.29
    container_name: dockhand
    restart: unless-stopped
    ports:
      - 3500:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ appdata_path }}/dockhand:/app/data"
    networks:
      - dockhand-net
    security_opt:
      - no-new-privileges:true

networks:
  dockhand-net:
