services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:v0.8.6-omnibus
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/nvme0:/dev/nvme0
    volumes:
      - "{{ appdata_path }}/scrutiny:/opt/scrutiny/config"
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    networks:
      - scrutiny-net
    restart: unless-stopped

networks:
  scrutiny-net:
