---
- name: install necessary packages
  apt:
    update_cache: yes
    name:
      - build-essential
      - git
      - libasound2-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavformat-dev
      - libavresample-dev
      - libdrm-common
      - libdrm-dev
      - libdrm2
      - libegl1-mesa-dev
      - libfreetype6-dev
      - libgbm-dev
      - libgbm1
      - libgles2
      - libgles2-mesa
      - libgles2-mesa-dev
      - libsdl-image1.2-dev
      - libsdl2-dev
      - libswresample-dev
      - libswscale-dev
      - libudev-dev
      - libv4l-dev
      - libxkbcommon-dev
      - libxml2-dev
      - yasm
      - zlib1g-dev
    state: present

### Build RetroArch
- name: Copy RetroArch build script
  copy:
    src: build.sh
    dest: /home/pi/build.sh
    owner: pi
    group: pi
    mode: +x

- name: get status of retroarch_install_path
  stat:
    path: /usr/local/bin/retroarch
  register: is_installed

- name: set retroarch installed
  set_fact:
    retroarch_is_installed: "{{ is_installed.stat.exists }}"

- name: get latest release
  uri:
    url: https://api.github.com/repos/libretro/retroarch/releases/latest
    return_content: true
  register: release_version_registered
  when: retroarch_download_latest_ver == True

- name: set retroarch version (latest)
  set_fact:
    retroarch_ver: "{{ release_version_registered.json.tag_name|regex_replace('v') }}"
  when: retroarch_download_latest_ver == True

- name: set retroarch version (pinned)
  set_fact:
    retroarch_ver: "{{ retroarch_pinned_ver }}"
  when: retroarch_download_latest_ver == False

- name: Build Retroarch
  command: sudo /usr/bin/bash build.sh {{ retroarch_ver|quote }}
  args:
    chdir: /home/pi
  when: retroarch_is_installed == False or ( retroarch_is_installed == True and retroarch_download_latest_ver == True ) or ( retroarch_is_installed == True and retroarch_download_latest_ver == False and retroarch_download_pinned_ver == True )

- name: Set bash profile to start retroarch
  copy:
    dest: /home/pi/.bash_profile
    owner: pi
    group: pi
    mode: 0664
    content: |
      if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
        exec retroarch >/dev/null 2>&1
      fi

### Syncthing
- name: Create .stignore file
  copy:
    dest: /mnt/roms/.stignore
    owner: "{{retroarch_user}}"
    group: "{{retroarch_user}}"
    mode: 0664
    content: |
      gc
      n64
      ps2
      wii
      lost+found
