---
### Basic Setup
- name: Set a hostname
  hostname:
    name: retroarch_pi

- name: create autologin directory
  file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory
    owner: ubuntu
    group: ubuntu

- name: disable login for user
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    owner: ubuntu
    group: ubuntu
    mode: 0664
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --skip-login --noissue --autologin ubuntu %I $TERM
      Type=idle

#- name: Add sudoers file for ubuntu
#  copy:
#    src: sudoer_ubuntu
#    dest: /etc/sudoers.d/ubuntu
#    owner: root
#    group: root
#    mode: 0440

- name: disable cloud-init
  file:
    path: /etc/cloud/cloud-init.disabled
    state: touch

- name: remove/purge snap
  apt:
    name: snapd
    state: absent
    purge: yes

- name: install bluetooth
  apt:
    name: 
      - pi-bluetooth
      - blueman
    state: present

# fstab/disk mounts
- name: make sure disks unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  with_items:
    - "{{ roms_drive }}"

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: "{{main_username}}"
    group: nobody
    mode: 0777
  with_items:
    - "{{ roms_drive }}"

- name: mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: mounted
  with_items:
    - "{{ roms_drive }}"

### Retroarch
- name: install retroarch
  include: install_retroarch.yml

### Hyperion
- name: install hyperion
  include: install_hyperion.yml