---
### Basic Setup
- name: Apt update
  apt:
    upgrade: 'yes'
    update_cache: yes
    cache_valid_time: 3600

- name: Set a hostname
  hostname:
    name: retroarchpi

- name: create autologin directory
  file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory
    owner: pi
    group: pi

- name: disable login for user
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
    owner: pi
    group: pi
    mode: 0664
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --skip-login --noissue --autologin pi %I $TERM
      Type=idle

- name: Set US locale
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Remove UK locale
  community.general.locale_gen:
    name: en_GB.UTF-8
    state: absent

- name: install bluetooth and other packages
  apt:
    name: 
      - pi-bluetooth
      - unzip
    state: present

# fstab/disk mounts
- name: make sure disks unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  with_items:
    - "{{ roms_drive }}"

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: pi
    group: pi
    mode: 0777
  with_items:
    - "{{ roms_drive }}"

- name: mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: mounted
  with_items:
    - "{{ roms_drive }}"

- name: set ownership
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: pi
    group: pi
    mode: 0777
  with_items:
    - "{{ roms_drive }}"

### Retroarch
- name: install retroarch
  include: install_retroarch.yml

### Hyperion
- name: install hyperion
  include: install_hyperion.yml