services:
  spoolman:
    image: ghcr.io/donkie/spoolman:0.23.1
    container_name: spoolman
    ports:
      - "7912:8000"
    volumes:
        - "{{ appdata_path}}/spoolman/data:/home/app/.local/share/spoolman"
    restart: unless-stopped
    environment:
      - TZ={{ ntp_timezone }}
    networks:
      - spoolman-net
    security_opt:
      - no-new-privileges:true

networks:
  spoolman-net: