---
- name: ensure destination for telegraf configuration file exists
  file:
    path: "{{ telegraf_config_path }}"
    state: directory
    owner: "{{ telegraf_config_user }}"
    group: "{{ telegraf_config_group }}"
    mode: 0755

- name: write telegraf conf file
  template:
    backup: yes
    src: ../templates/telegraf.conf.j2
    dest: "{{ telegraf_config_path }}/telegraf.conf"
    owner: "{{ telegraf_config_user }}"
    group: "{{ telegraf_config_group }}"

- name: Add Telegraf user to docker group
  user:
    name: telegraf
    groups: docker
    append: yes
  when: telegraf_influx_docker == true

- name: Enable/Start Telegraf
  systemd:
    enabled: true
    daemon-reload: true
    state: restarted
    name: telegraf
