services:
  bambuddy:
    image: ghcr.io/maziggy/bambuddy:0.2.4.3
    container_name: bambuddy
    volumes:
      - "{{ appdata_path }}/bambuddy/data:/app/data"
      - "{{ appdata_path }}/bambuddy/logs:/app/logs"
    ports:
      - 9500:9000
    environment:
      - TZ={{ ntp_timezone }}
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - PORT=8000
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  mobileraker-companion:
    image: ghcr.io/clon1998/mobileraker_companion:latest
    container_name: mobileraker-companion
    volumes:
    - "{{ appdata_path }}/mobileraker/mobileraker.conf:/opt/printer_data/config/mobileraker.conf"
    networks:
      - mobileraker-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  mobileraker-net: