services:
  paperless-redis:
    image: redis:8.6.2
    container_name: paperless-redis
    networks:
      - paperless-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.15
    container_name: paperless
    volumes:
      - "{{ appdata_path }}/paperless/data:/usr/src/paperless/data"
      - "{{ appdata_path }}/paperless/media:/usr/src/paperless/media"
      - "{{ appdata_path }}/paperless/export:/usr/src/paperless/export"
      - "/mnt/Media/Files/scans:/usr/src/paperless/consume"
    ports:
      - 8100:8000
    environment:
      - PAPERLESS_REDIS=redis://paperless-redis:6379
      - PAPERLESS_TIME_ZONE={{ ntp_timezone }}
      - PAPERLESS_URL=https://paperless.{{ secret_personal_url }}
      - PAPERLESS_SECRET_KEY={{ secret_paperless_key }}
      - PAPERLESS_FILENAME_FORMAT={% raw %}{{ added_year }}/{{ document_type }}/{{ title }}{% endraw %}
      - USERMAP_UID={{ main_uid }}
      - USERMAP_GID={{ main_gid }}
      - PAPERLESS_APPS=allauth.socialaccount.providers.openid_connect
      - PAPERLESS_SOCIALACCOUNT_PROVIDERS={"openid_connect":{"SCOPE":["openid","profile","email"],"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"pocket-id","name":"Pocket-ID","client_id":"{{ secret_paperless_pocket_id_user }}","secret":"{{ secret_paperless_pocket_id_key }}","settings":{"server_url":"https://id.{{ secret_personal_url }}"}}]}}
      - PAPERLESS_CONSUMER_POLLING=60
    networks:
      - paperless-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  paperless-net:
