---
- name: create folderspoints
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ pegasus_user }}"
    group: "{{ pegasus_user }}"
    mode: 0755
  with_items:
    - "{{ pegasus_metadata_dir }}"
    - "{{ pegasus_roms_dir }}"
    - "{{ pegasus_metadata_dir }}/apps"
    - "{{ pegasus_config_dir }}/themes"
    - "{{ pegasus_config_dir }}/theme_settings"

- name: copy files
  copy:
    src: "{{ item.name }}"
    dest: "{{ item.path }}"
    owner: "{{ pegasus_user }}"
    group: "{{ pegasus_user }}"
    mode: 0644
  with_items:
    - name: settings.txt
      path: "{{ pegasus_config_dir }}/settings.txt"
    - name: artwork.xml
      path: "{{ pegasus_metadata_dir }}/artwork.xml"
    - name: gameOS.json
      path: "{{ pegasus_config_dir }}/theme_settings/gameOS-master.json"

- name: create template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ pegasus_user }}"
    group: "{{ pegasus_user }}"
    mode: "{{ item.mode | default(0644) }}"
  with_items:
    - src: config.ini.j2
      dest: "{{ skyscraper_config_path }}"
    - src: game_dirs.txt.j2
      dest: "{{ pegasus_config_dir }}/game_dirs.txt"
    - src: scrape.sh.j2
      dest: "{{ pegasus_metadata_dir }}/scrape.sh"
      mode: +x

- name: download theme
  unarchive:
    src: https://github.com/PlayingKarrde/gameOS/archive/refs/heads/master.zip
    dest: "{{ pegasus_config_dir }}/themes"
    remote_src: yes
    owner: "{{ pegasus_user }}"
    group: "{{ pegasus_user }}"
    mode: 0666

- name: download app metadata
  unarchive:
    src: https://github.com/FuzzyMistborn/infra/raw/main/roles/config_pegasus/files/metadata/apps_pegasus.tar.gz
    dest: "{{ pegasus_metadata_dir }}/apps"
    remote_src: yes
    owner: "{{ pegasus_user }}"
    group: "{{ pegasus_user }}"
    mode: 0666
  when: ansible_hostname == 'RetroArch-TV'