---

- name: create config directories
  file:
    path: "/home/{{main_username}}/{{ item }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  loop:
    - docker
    - docker/bitwarden_db
    - docker/diun
    - docker/nextcloud_db
    - docker/wallabag_db
    - docker/hass_db
    - docker/influxdb
    - db_backups
    - scripts

### Telegraf
- name: Install Telegraf
  apt:
    deb: https://dl.influxdata.com/telegraf/releases/telegraf_{{telegraf_ver}}-1_amd64.deb
- name: Copy Telegraf config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 0644
- name: Add Telegraf user to docker group
  user:
    name: telegraf
    groups: docker
    append: yes
- name: Enable/Start Telegraf
  systemd:
    enabled: true
    daemon-reload: true
    state: restarted
    name: telegraf

#### DIUN
- name: Copy DIUN Config Template
  template:
    src: diun_config.yml.j2
    dest: /home/{{ main_username }}/docker/diun/config.yml
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

- name: Copy db backup script template
  template:
    src: "{{item.src}}"
    dest: /home/{{ main_username }}/scripts/{{item.dest}}
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
  with_items:
    - { src: 'db_backup.sh.j2', dest: 'db_backup.sh' }
    - { src: 'db_restore.sh.j2', dest: 'db_restore.sh' }

### Restic
- name: Add Synology SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/synology_restic
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_synology_restic_key }}"

- name: Check that Synology not already in SSH config
  shell: grep -c "Host synology" /home/{{main_username}}/.ssh/config || true
  register: synology_ssh

- name: Add ssh config for Synology
  lineinfile:
    path: /home/{{ main_username }}/.ssh/config
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0664
    line: |
      Host synology
        HostName 192.168.30.25
        User {{main_username}}
        IdentityFile ~/.ssh/synology_restic
    create: true
  when: synology_ssh.stdout == "0" or synology_ssh.stdout == ""

- name: Update Restic to latest version
  command: "/usr/bin/restic self-update"
- name: Install Autorestic
  shell: curl -s https://raw.githubusercontent.com/CupCakeArmy/autorestic/master/install.sh | sudo bash
  
- name: Copy Autorestic Config Template
  template:
    src: autorestic.yml.j2
    dest: /home/{{ main_username }}/.autorestic.yml
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

### Backup Restore
- name: Restore folders from backup
  command: "/usr/local/bin/autorestic restore -f -l {{item.name}} --from {{item.src}} --to {{item.dest}}"
  with_items:
    - { name: "db_backups", src: 'synology_db', dest: '/home/{{main_username}}' }
  when: pull_backup == "true"

#### Restore Folders
- name: restore folders from backup
  copy:
    src: /mnt/Backup/{{item.src}}
    dest: "/home/{{ main_username }}/{{item.dest}}"
    remote_src: true
    mode: preserve
  with_items:
    - { src: 'db_backups', dest: '' }
  when: pull_backup == "true"

#### Restore Databases
- name: Run DB Restore Script
  command: /bin/bash ./db_restore.sh
  args:
    chdir: "/home/{{main_username}}/scripts"
  when: pull_backup == "true"

#### Cronjobs
- name: "Main User Cronjobs"
  cron:
    user: "{{ main_username }}"
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    weekday: "{{ item.weekday }}"
    state: present
  loop:
    - { job: "/home/{{ main_username }}/scripts/db_backup.sh", name: "DB Backup", hour: "0", minute: "45", weekday: "*" }