---
- name: Copy certs script
  template:
    src: "{{item.src}}"
    dest: /home/{{ main_username }}/{{item.dest}}
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
  with_items:
    - {src: 'certs.sh.j2', dest: 'certs.sh'}

### LEGO variable
- name: populate /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^LINODE_TOKEN="
    line: "LINODE_TOKEN={{secret_linode_token}}"
