services:
  diun:
    image: crazymax/diun:4.29.0
    container_name: diun
    volumes:
      - "{{ appdata_path }}/diun/data:/data"
      - "{{ appdata_path }}/diun/config.yml:/diun.yml:ro"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UID={{ main_uid }}
      - GID={{ main_gid }}
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ ntp_timezone }}
      - LOG_LEVEL=info
      - LOG_JSON=false
    hostname: invention
    restart: always
  portainer_agent:
    image: portainer/agent:2.25.1
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    environment:
      - AGENT_SECRET={{ secret_portainer_key }}
    restart: always
  minecraft:
    image: 05jchambers/legendary-minecraft-geyser-floodgate:latest
    container_name: minecraft
    volumes:
      - "{{ appdata_path }}/minecraft:/minecraft"
    labels:
      - diun.enable=true
      - diun.regopt=docker.io
    ports:
      - 25565:25565
      - 19132:19132/udp
      - 19132:19132
    restart: unless-stopped