---

### Basic Setup/Boostrap
- name: Ensure user groups exists
  group:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ main_username }}"
    - ansible

- name: Add users
  user:
    name: "{{ item.user }}"
    password: "{{ item.pass }}"
    groups:
      - "{{ item.user }}"
      - sudo
    shell: /bin/bash
  loop:
    - {user: "{{ main_username }}", pass: "{{ secret_main_user_pass }}"}
    - {user: ansible, pass: "{{ secret_ansible_pass }}"}

- name: Add sudoers file for ansible
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: SSH Keys
  authorized_key:
    user: "{{ item.user }}"
    state: present
    key: "{{ item.ssh }}"
  loop:
    - {user: "{{ main_username }}", ssh: "{{ secret_main_user_ssh }}"}
    - {user: "{{ main_username }}", ssh: "{{ secret_main_user_alt_ssh }}"}
    - {user: ansible, ssh: "{{ secret_ansible_ssh }}"}

- name: create main user directories
  file:
    path: /home/{{ main_username }}/{{ item }}
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  loop:
    - docker
    - docker/immich
    - docker/ollama

### GPU
- name: Add Nvidia repo gpg key
  apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present

- name: Add Nvidia apt repo
  get_url:
    url: https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    mode: 0644

#- name: Install Nvidia
#  command: sudo ubuntu-drivers install
#  become: true

- name: Install Nvidia container toolkit
  apt:
    name:
      - nvidia-container-toolkit
    state: present
    update_cache: yes

### fstab/disk mounts
- name: make sure disks unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  loop: "{{ mountpoints }}"

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0777
  loop: "{{ mountpoints }}"

- name: Add smbcredentials
  copy:
    dest: /home/{{ main_username }}/.smbcredentials
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: |
      user=samba
      password={{ secret_samba_pass }}
      domain=cosmere

- name: mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: present
  loop: "{{ mountpoints }}"
