---
- name: check whether package is installed
  shell: "dpkg-query -W 'pve-fake-subscription'"
  ignore_errors: true
  register: is_installed
  changed_when: "is_installed.rc != 0"

- name: install package?
  set_fact:
    force_install: "{{ nag_force_install == true or is_installed.failed == true }}"

- name: get latest release
  uri:
    url: https://api.github.com/repos/Jamesits/pve-fake-subscription/releases/latest
    return_content: true
  register: release_latest
  when: nag_ver is undefined and force_install == True

- name: set version if not already
  set_fact: nag_ver="{{ release_latest.json.tag_name }}"
  when: nag_ver is undefined and force_install == True

- name: download release
  when: force_install == True
  get_url:
    url: https://github.com/Jamesits/pve-fake-subscription/releases/download/{{nag_ver}}/pve-fake-subscription_{{nag_ver | regex_replace('v') }}_all.deb
    dest: /tmp

- name: set filename
  set_fact: file_name="pve-fake-subscription_{{nag_ver | regex_replace('v') }}_all.deb"
  when: force_install == True

- name: install deb
  apt:
    deb: /tmp/{{ file_name }}
    state: present
  when: force_install == True
