services:
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    restart: always
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS="north-america.pool.ntp.org,time.nist.gov,0.fedora.pool.ntp.org,0.debian.pool.ntp.org"
      - LOG_LEVEL=0
      - TZ={{ ntp_timezone }}
    networks:
      - ntp-net
    security_opt:
      - no-new-privileges:true

networks:
  ntp-net:
