---
- name: "Create Mopidy configuration directory"
  become: true
  file:
    path: /etc/mopidy
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Configure Mopidy"
  become: true
  template:
    src: templates/mopidy.conf.j2
    dest: /etc/mopidy/mopidy.conf
    owner: mopidy
    group: root
    mode: 0640
  notify:
    - restart mopidy

- name: "Create Mopidy Music directory"
  become: true
  file:
    path: /home/{{ mopidy_user }}/Music
    state: directory
    owner: "{{ mopidy_user }}"
    group: "{{ mopidy_user }}"
    mode: 0755
