---
- name: "Ensure GnuPG is installed"
  apt:
    name: gnupg
    state: present

- name: "Add Mopidy APT key"
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: "Add Mopidy APT repo"
  become: true
  apt_repository:
    repo: deb http://apt.mopidy.com/ buster main contrib non-free
    state: present
    filename: mopidy
    update_cache: yes

- name: "Install Mopidy"
  become: true
  apt:
    name: "mopidy"
    state: present
  notify:
    - restart mopidy

- name: "Install Iris/Jellyfin plugins via pip"
  become: true
  pip:
    executable: pip3
    name: "{{ item }}"
    state: present
  with_items:
    - Mopidy-Iris
    - Mopidy-Jellyfin
    - Mopidy-mpd
    - Mopidy-Local
  notify:
    - restart mopidy

- name: "Ensure Mopidy starts at boot"
  become: true
  service:
    name: mopidy
    enabled: true
    state: restarted
