---

# fstab/disk mounts
- name: make sure disks unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  with_items:
    - "{{ data_disks }}"

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: "{{ main_username }}"
    group: nobody
    mode: 0777
  with_items:
    - "{{ data_disks }}"

- name: mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: mounted
  with_items:
    - "{{ data_disks }}"

### Logiops
- name: Copy logid.cfg file
  copy:
    src: logid.cfg
    dest: /etc/logid.cfg
    owner: root
    group: root
    mode: 0644

### Dolphin
- name: Copy config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
  with_items:
    - src: "kde/dolphinrc"
      dest: "/home/{{ main_username }}/.config/dolphinrc"
    - src: "kde/khotkeysrc"
      dest: "/home/{{ main_username }}/.config/khotkeysrc"
    - src: "kde/dolphinui.rc"
      dest: "/home/{{ main_username }}/.local/share/kxmlgui5/dolphin/dolphinui.rc"
    - src: "kde/konsoleprofile"
      dest: "/home/{{ main_username }}/.local/share/konsole/ZSH.profile"
    - src: "kde/Default.layout.latte"
      dest: "/home/{{ main_username }}/.config/latte/Default.layout.latte"
