---
### Packages
- name: Install Custom Kelsier Packages
  ansible.builtin.package:
    name:
      - "{{ item.name }}"
    state: present
  loop: "{{ kelsier_package_list }}"

### AUR
- name: Install AUR Packages
  kewlfft.aur.aur:
    use: yay
    name:
      - "{{ item.name }}"
    state: present
  become_user: ansible
  become: yes
  loop: "{{ kelsier_aur_package_list }}"

# fstab/disk mounts
- name: make sure disks unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  loop: "{{ data_disks }}"

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: "{{ main_username }}"
    group: nobody
    mode: 0777
  loop: "{{ data_disks }}"

- name: mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: mounted
  loop: "{{ data_disks }}"

# - name: Enable WOL ethtool
#   command: ethtool -s enp0s31f6 wol bg

- name: Enable WOL nmcli
  command: sudo nmcli c modify "Wired connection 1" 802-3-ethernet.wake-on-lan magic