services:
  nut-ups:
    image: fuzzymistborn/nut-upsd:2.8.2
    container_name: nut-ups
    devices:
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 3493:3493
    environment:
      - API_USER=homeassistant
      - API_PASSWORD={{ secret_nut_api_pw }}
    networks:
      - nut-ups-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  nut-ups-net:
