---
- name: restart wireguard service
  service:
    name: wg-quick@wg0
    enabled: 'true'
    state: restarted

- name: start wireguard service
  service:
    name: wg-quick@wg0
    enabled: 'true'
    state: started

- name: start adguard
  command: /opt/AdGuardHome/AdGuardHome -s start

- name: stop adguard
  command: /opt/AdGuardHome/AdGuardHome -s stop

- name: restart adguard
  command: /opt/AdGuardHome/AdGuardHome -s restart