---

- name: make sure disks unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  loop: "{{ data_disks + parity_disks + nfs_mount }}"

- name: create /mnt points
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  loop: "{{ mergerfs_mount + data_disks + parity_disks + nfs_mount + external_mount }}"

- name: mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: mounted
  loop: "{{ data_disks + parity_disks }}"

- name: NFS mounts to fstab
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: present
  loop: "{{ nfs_mount }}"

- name: mount mergerfs array
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.source }}"
    opts: "{{ item.opts }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: mounted
  loop: "{{ fstab_mergerfs }}"
