---

- name: make sure hard drive disks unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  loop: "{{ disks }}"

- name: make sure nfs unmounted
  mount:
    path: "{{ item.path }}"
    state: unmounted
  loop: "{{ nfs_mount }}"

- name: create mergerfs mountpoint
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  loop: "{{ mergerfs_mount }}"

- name: create disks mountpoints
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  loop: "{{ disks }}"

- name: create nfs mountpoints
  file:
    dest: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777
  loop: "{{ nfs_mount }}"

- name: create external hdd mount point
  file:
    dest: /media/external_hdd
    state: directory
    owner: nobody
    group: nogroup
    mode: 0777

- name: mount disks
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: mounted
  loop: "{{ disks }}"

- name: NFS mounts to fstab
  mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: present
  loop: "{{ nfs_mount }}"

- name: mount mergerfs array
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.source }}"
    opts: "{{ item.opts }}"
    fstype: "{{ item.fs }}"
    # change to 'mounted' to auto mount versus 'present' for just loaded into fstab
    state: mounted
  loop: "{{ fstab_mergerfs }}"
