---
### Create LXCs

- name: Update pveam
  command: pveam update

- name: Download container templates
  command: pveam download NFS {{ item }}
  loop:
    - ubuntu-24.04-standard_24.04-2_amd64.tar.zst
    - debian-12-standard_12.2-1_amd64.tar.zst.tmp

- name: Create LXCs w/ VLAN Tags
  proxmox:
    vmid: "{{ item.vmid }}"
    hostname: "{{ item.name }}"
    unprivileged: "{{ not item.privileged }}"
    onboot: "{{ item.onboot | default ('true') }}"
    state: present
    node: adonalsium
    storage: local-lvm
    disk: "{{ item.disk }}"
    cpus: '1'
    cpuunits: '1000'
    cores: "{{ item.cores }}"
    memory: "{{ item.memory }}"
    swap: "{{ item.swap | default ('512') }}"
    api_user: root@pam
    api_host: localhost
    api_token_id: Ansible
    api_token_secret: "{{ secret_proxmox_api_token }}"
    pubkey: "{{ secret_proxmox_ct_ssh }}"
    password: "{{ secret_proxmox_pass }}"
    netif: "{'net0':'name=eth0,gw={{ item.gw }},ip={{ item.ip }}/24,tag={{ item.tag | default ('50') }},bridge=vmbr1'}"
    ostemplate: "{{ item.template| default ('NFS:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst') }}"
    features:
      - nesting={{ item.nesting | default ('1') }}
      # - keyctl={{ item.keyctl | default ('0') }}
  loop: "{{ lxc_vlans }}"

- name: Create LXC CT w/ Mounts
  proxmox:
    vmid: "{{ item.vmid }}"
    hostname: "{{ item.name }}"
    unprivileged: "{{ not item.privileged }}"
    onboot: "{{ item.onboot | default ('true') }}"
    state: present
    node: adonalsium
    storage: local-lvm
    disk: "{{ item.disk }}"
    cpus: '1'
    cpuunits: '1000'
    cores: "{{ item.cores }}"
    memory: "{{ item.memory }}"
    swap: "{{ item.swap | default ('512') }}"
    api_user: root@pam
    api_host: localhost
    api_token_id: Ansible
    api_token_secret: "{{ secret_proxmox_api_token }}"
    pubkey: "{{ secret_proxmox_ct_ssh }}"
    password: "{{ secret_proxmox_pass }}"
    netif: "{'net0':'name=eth0,gw={{ item.gw }},ip={{ item.ip }}/24,tag={{ item.tag | default ('50') }},bridge=vmbr1'}"
    ostemplate: "{{ item.template| default ('NFS:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst') }}"
    mounts: "{'mp0':'/dev/disk/by-id/ata-KINGSTON_SA400S37480G_50026B7785A010DF-part1,mp=/mnt/scratch,backup=0'}"
  loop: "{{ lxc_mounts }}"

- name: Add features to LXC CT w/ Mounts
  shell: pct set {{ item.vmid }} --features nesting={{ item.nesting | default('0') }},mount={{ item.fsmount }}
  loop: "{{ lxc_mounts }}"

- name: Create VM with UEFI Secure Boot Enabled
  community.general.proxmox_kvm:
    api_user: root@pam
    api_host: localhost
    api_token_id: Ansible
    api_token_secret: "{{ secret_proxmox_api_token }}"
    name: "{{ item.name }}"
    node: adonalsium
    vmid: "{{ item.vmid }}"
    onboot: "{{ item.onboot | default ('false') }}"
    net:
      net0: "virtio,bridge={{ item.bridge | default ('vmbr1') }},tag={{ item.tag | default ('50') }},firewall=1"
    cores: "{{ item.cores }}"
    cpu: "{{ item.cpu_type | default ('kvm64') }}"
    memory: "{{ item.memory }}"
    balloon: "{{ item.balloon }}"
    bios: "{{ item.bios | default ('seabios') }}"
    scsihw: virtio-scsi-single
    scsi:
      scsi0: "{{ item.disk }},ssd=1,iothread=1"
    format: qcow2
    ide:
      ide2: "NFS:iso/{{ item.iso | default ('ubuntu-24.04-live-server-amd64.iso') }},media=cdrom"
    efidisk0:
      storage: local-lvm
      format: raw
      efitype: 4m
      pre_enrolled_keys: 1
  loop: "{{ vm_uefi }}"

- name: Set boot order
  shell: pct set {{ item.lxc }} --startup order={{ item.order }}
  loop:
    - {"lxc":"201", "order":"1"}
    - {"lxc":"250", "order":"3"}
    - {"lxc":"251", "order":"3"}
    - {"lxc":"252", "order":"3"}
    - {"lxc":"253", "order":"2"}

- name: Autonomy - Add USB devices
  lineinfile:
    dest: "/etc/pve/lxc/251.conf"
    insertafter: EOF
    line: |
      lxc.apparmor.profile: unconfined
      lxc.cgroup2.devices.allow: a
      lxc.cap.drop:
    unsafe_writes: yes

# Add PCI Passthrough for Virtuosity
- name: Get current VM configuration
  shell: "qm config {{ item.vmid }}"
  register: current_vm_config
  changed_when: false
  loop: "{{ vm_uefi }}"

- name: Find next available hostpci slot
  shell: |
    qm config {{ item.vmid }} | grep -E "^hostpci[0-9]:" | sed 's/hostpci\([0-9]\+\):.*/\1/' | sort -n | tail -1
  register: last_hostpci_slot
  changed_when: false
  failed_when: false
  loop: "{{ vm_uefi }}"

- name: Add PCIe passthrough device to VM configuration
  shell: |
    LAST_SLOT=$(qm config {{ item.vmid }} | grep -E "^hostpci[0-9]:" | sed 's/hostpci\([0-9]\+\):.*/\1/' | sort -n | tail -1)
    NEXT_SLOT=$((${LAST_SLOT:-0} + 1))
    qm set {{ item.vmid }} -hostpci${NEXT_SLOT} {{ item.pcie }}
    echo "Added {{ item.pcie }} as hostpci${NEXT_SLOT} to VM {{ item.name }} ({{ item.vmid }})"
  register: add_pcie_result
  loop: "{{ vm_uefi }}"

- name: Display PCIe addition results
  debug:
    msg: "{{ item.stdout }}"
  loop: "{{ add_pcie_result.results }}"