services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:v2.14.1
    container_name: linkwarden
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL={{secret_linkwarden_db_url}}
      - NEXTAUTH_URL=https://linkwarden.{{ secret_personal_url }}/api/v1/auth
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000/api/v1/auth
      - NEXTAUTH_SECRET={{ secret_linkwarden_nextauth }}
      - NEXT_PUBLIC_DISABLE_REGISTRATION=true
      - NEXT_PUBLIC_KEYCLOAK_ENABLED=true
      - KEYCLOAK_CUSTOM_NAME=PocketID
      - KEYCLOAK_ISSUER=https://id.{{ secret_personal_url }}
      - KEYCLOAK_CLIENT_ID={{ secret_linkwarden_pocket_id_user }}
      - KEYCLOAK_CLIENT_SECRET={{ secret_linkwarden_pocket_id_key }}
      - CUSTOM_OPENAI_BASE_URL=192.168.50.25:8080/v1
      - OPENAI_MODEL=emma-4-e4b
      - OPENAI_API_KEY=
#      - ANTHROPIC_API_KEY={{ secret_linkwarden_anthropic_api_key }}
#      - ANTHROPIC_MODEL=claude-3-5-haiku-latest
    volumes:
      - "{{ appdata_path }}/linkwarden/data:/data/data"
    networks:
      - linkwarden-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  linkwarden-meilisearch:
    image: getmeili/meilisearch:v1.42.1
    container_name: linkwarden-meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY={{ secret_meilisearch_key }}
      - MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE=true
    volumes:
      - "{{ appdata_path }}/linkwarden/meili_data:/meili_data"
    networks:
      - linkwarden-net
    security_opt:
      - no-new-privileges:true

networks:
  linkwarden-net:
