services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:0.25.0
    container_name: homebox
    restart: unless-stopped
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=20
      - HBOX_OPTIONS_ALLOW_REGISTRATION=false
      - HBOX_LABEL_MAKER_PRINT_COMMAND=mosquitto_pub -h 192.168.30.5 -u homeassistant -P {{ secret_mqtt_pass }} -t homebox/labels --retain -f {{'{{'}}.FileName}}
      - HBOX_LABEL_MAKER_PADDING=5
      - HBOX_LABEL_MAKER_MARGIN=5
      - HBOX_LABEL_MAKER_WIDTH=320
      - HBOX_LABEL_MAKER_HEIGHT=96
      - HBOX_LABEL_MAKER_FONT_SIZE=24
      - HBOX_LABEL_MAKER_DYNAMIC_LENGTH=false
      - HBOX_MAILER_PORT=587
      - HBOX_MAILER_USERNAME={{ secret_snapraid_email_address }}
      - HBOX_MAILER_PASSWORD={{ secret_snapraid_email_pass }}
      - HBOX_MAILER_FROM=homebox@{{ secret_personal_url }}
      - HBOX_OPTIONS_TRUST_PROXY=true
      - HBOX_OIDC_ENABLED=true
      - HBOX_OIDC_ISSUER_URL=https://id.{{ secret_personal_url }}
      - HBOX_OIDC_CLIENT_ID={{ secret_homebox_pocket_id_user }}
      - HBOX_OIDC_CLIENT_SECRET={{ secret_homebox_pocket_id_key }}
      - HBOX_OIDC_BUTTON_TEXT=Sign in with PocketID
      - HBOX_OPTIONS_ALLOW_ANALYTICS=false
    volumes:
      - "{{ appdata_path }}/homebox/data:/data/"
      - "{{ appdata_path }}/homebox/labels:/labels/"
    ports:
      - 7745:7745
    networks:
      - homebox-net
    security_opt:
      - no-new-privileges:true

networks:
  homebox-net:
