---
- name: Clone Eupnea Audio-Scripts GitHub Repo
  git:
    repo: git@github.com:eupnea-linux/audio-scripts.git
    dest: /home/{{ main_username }}/audio-scripts

- name: Enable rotate sensor
  systemd:
    enabled: true
    daemon-reload: true
    state: restarted
    name: iio-sensor-proxy

- name: Enable bluetooth
  systemd:
    enabled: true
    daemon-reload: true
    state: restarted
    name: bluetooth