services:
  traccar:
    image: traccar/traccar:6.13.2
    container_name: traccar
    ports:
      - 127.0.0.1:8082:8082
      - 5030:5030
    environment:
      - CONFIG_USE_ENVIRONMENT_VARIABLES=true
      - DATABASE_DRIVER=org.postgresql.Driver
      - DATABASE_URL=jdbc:postgresql://traccar-db:5432/traccar
      - DATABASE_USER=traccar
      - DATABASE_PASSWORD={{ secret_traccar_db_pass }}
      - STORAGE_TIME=14
      - REGISTRATION_ENABLE=false
      - WEB_URL=https://traccar.fuzzymistborn.com
      - OPENID_CLIENT_ID={{ secret_traccar_oidc_client_id }}
      - OPENID_CLIENT_SECRET={{ secret_traccar_oidc_client_secret }}
      - OPENID_ISSUER_URL=https://id.{{ secret_personal_url }}
      - OPENID_FORCE=true
    depends_on:
      - traccar-db
    networks:
      - traccar-net
    volumes:
      - "{{ appdata_path }}/traccar/logs:/opt/traccar/logs"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  traccar-db:
    image: pgautoupgrade/pgautoupgrade:18.3-alpine
    container_name: traccar-db
    environment:
      - POSTGRES_DB=traccar
      - POSTGRES_USER=traccar
      - POSTGRES_PASSWORD={{ secret_traccar_db_pass }}
    volumes:
      - "{{ appdata_path }}/traccar/postgres/data:/var/lib/postgresql"
    networks:
      - traccar-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  traccar-net:
