services:
  crowdsec:
    image: ghcr.io/crowdsecurity/crowdsec:v1.7.8
    container_name: crowdsec
    volumes:
      - "{{ appdata_path }}/crowdsec/data/acquis.yaml:/etc/crowdsec/acquis.yaml"
      - "{{ appdata_path }}/vaultwarden/data/log:/var/log/vaultwarden:ro"
      - "{{ appdata_path }}/crowdsec/db:/var/lib/crowdsec/data/"
    environment:
      - COLLECTIONS=Dominic-Wagner/vaultwarden
      - GID=1000
      - DISABLE_LOCAL_API=true
      - AGENT_USERNAME={{ hostname }}
      - AGENT_PASSWORD={{ secret_crowdsec_cultivation_pw }}
      - LOCAL_API_URL=http://{{ secret_ambition_ip }}:8080
    networks:
      - crowdsec-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  crowdsec-net:
