---
- name: Set a hostname
  hostname:
    name: retroarch-tv

- name: SSH Keys
  authorized_key:
    user: retro
    state: present
    key: "{{ item }}"
  loop:
    - "{{ secret_main_user_ssh }}"
    - "{{ secret_main_user_alt_ssh }}"

- name: create /media/roms
  file:
    dest: /media/roms
    state: directory
    owner: retro
    group: retro
    mode: 0777

### Flatpak
- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system

- name: Install flatpaks
  community.general.flatpak:
    name:
      - com.valvesoftware.SteamLink
    state: present
    method: user
  become_user: retro
  become: yes

- name: Enable WOL ethtool
  command: ethtool -s eno1 wol g

- name: enable WOL tlp.conf
  lineinfile:
    dest: "/etc/tlp.conf"
    state: present
    regexp: "^WOL_DISABLE"
    line: "WOL_DISABLE=N"

- name: Reload TLP/Cronie/bluetooth
  systemd:
    enabled: true
    daemon-reload: true
    state: restarted
    name: "{{ item }}"
  with_items:
    - tlp
    - cronie
    - bluetooth

- name: enable bluetooth auto-power on
  lineinfile:
    dest: "/etc/bluetooth/main.conf"
    state: present
    regexp: "^AutoEnable"
    line: "AutoEnable=true"

- name: Set bash profile to start retroarch
  copy:
    dest: /home/retro/.bash_profile
    owner: retro
    group: retro
    mode: 0664
    content: |
      if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
        exec retroarch >/dev/null 2>&1
      fi
