---
- name: SSH Keys
  authorized_key:
    user: retro
    state: present
    key: "{{ item }}"
  loop:
    - "{{ secret_main_user_ssh }}"
    - "{{ secret_main_user_alt_ssh }}"
    - "{{ secret_main_user_pixel_ssh }}"

- name: Fix SFTP for Ansible
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    state: present
    regexp: "Subsystem sftp*"
    line: "Subsystem sftp internal-sftp"

- name: Restart ssh
  service:
    name: sshd
    state: restarted

- name: create folderspoints
  file:
    dest: "{{ item }}"
    state: directory
    owner: retro
    group: retro
    mode: 0777
  with_items:
    - /media/roms

### AUR
- name: Install AUR Packages
  kewlfft.aur.aur:
    use: yay
    name:
      - "{{ item.name }}"
    state: present
  become_user: ansible
  become: yes
  with_items:
    - "{{ aur_package_list }}"

- name: Disable screen autolock
  ini_file:
    path: /home/retro/.config/kscreenlockerrc
    section: Daemon
    option: "{{item}}"
    value: 'false'
    mode: '0600'
  with_items:
    - Autolock
    - LockOnResume

- name: Enable WOL ethtool
  command: ethtool -s eno1 wol g

- name: Enable WOL nmcli
  command: sudo nmcli c modify "Wired connection 1" 802-3-ethernet.wake-on-lan magic

- name: enable WOL tlp.conf
  lineinfile:
    dest: "/etc/tlp.conf"
    state: present
    regexp: "^WOL_DISABLE"
    line: "WOL_DISABLE=N"

- name: Reload TLP/Cronie/bluetooth
  systemd:
    enabled: true
    daemon-reload: true
    state: restarted
    name: "{{ item }}"
  with_items:
    - tlp
    - cronie
    - bluetooth

- name: enable bluetooth auto-power on
  lineinfile:
    dest: "/etc/bluetooth/main.conf"
    state: present
    regexp: "^AutoEnable"
    line: "AutoEnable=true"

- name: add bash_aliases source to bashrc
  lineinfile:
    dest: /home/retro/.bashrc
    state: present
    regexp: "source ~/.bash_aliases"
    line: "source ~/.bash_aliases"
