services:
  llama-swap:
    image: ghcr.io/mostlygeek/llama-swap:unified-cuda-2026-05-13
    container_name: llama-swap
    volumes:
      - /mnt/llms/models:/models:ro
      - "{{ appdata_path }}/llama/config.yml:/etc/llama-swap/config/config.yaml:ro"
    ports:
      - 8080:8080
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - llama-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.9.5
    container_name: open-webui
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - "{{ appdata_path }}/open-webui:/app/backend/data"
    ports:
      - 3010:8080
    environment:
      - WEBUI_SECRET_KEY={{ secret_webui_secret_key }}
      - OPENAI_API_BASE_URL=http://llama-swap:8080/v1
      - OPENAI_API_KEY=none
    networks:
      - llama-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  llama-net:
