services:
  adguard:
    image: adguard/adguardhome:v0.107.74
    container_name: adguard
    cap_add:
      - NET_ADMIN
    volumes:
      - "{{ appdata_path }}/adguard/conf:/opt/adguardhome/conf"
      - "{{ appdata_path }}/adguard/work:/opt/adguardhome/work"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 81:80/tcp
      - 444:443/tcp
      - 3000:3000/tcp
    networks:
      - adguard-net
    restart: unless-stopped
  adguard-sync:
    image: ghcr.io/linuxserver/adguardhome-sync:0.9.0
    container_name: adguard-sync
    volumes:
      - "{{ appdata_path }}/adguardsync/config:/config"
    ports:
      - 8080:8080
    environment:
      - UID={{ main_uid }}
      - GID={{ main_gid }}
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ ntp_timezone }}
    networks:
      - adguard-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  adguard-net:
