services:
  adguard:
    image: adguard/adguardhome:v0.107.63
    container_name: adguard
    cap_add:
      - NET_ADMIN
    volumes:
      - "{{ appdata_path }}/adguard/conf:/opt/adguardhome/conf"
      - "{{ appdata_path }}adguard/work:/opt/adguardhome/work"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 81:80/tcp
      - 444:443/tcp
      - 3000:3000/tcp
    restart: unless-stopped
  crowdsec:
    image: ghcr.io/crowdsecurity/crowdsec:v1.6.10
    container_name: crowdsec
    volumes:
      - "{{ appdata_path }}/crowdsec/data/acquis.yaml:/etc/crowdsec/acquis.yaml"
      - /var/log/auth.log:/var/log/ssh/auth.log:ro
      - "{{ appdata_path }}/crowdsec/db:/var/lib/crowdsec/data/"
    environment:
      - COLLECTIONS=crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/sshd
      - GID=1000
      - DISABLE_LOCAL_API=true
      - AGENT_USERNAME={{ hostname }}
      - AGENT_PASSWORD={{ secret_crowdsec_honor_pw }}
      - LOCAL_API_URL=http://{{ secret_ambition_ip }}:8080
    restart: unless-stopped
  portainer_agent:
    image: portainer/agent:2.31.3
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    environment:
      - AGENT_SECRET={{ secret_portainer_key }}
    restart: unless-stopped
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1.6.4
    container_name: pocket-id
    restart: unless-stopped
    environment:
      - APP_NAME=Identity
      - APP_URL=https://id.{{ secret_personal_url }}
      - TRUST_PROXY=true
      - SESSION_DURATION=120
      - MAXMIND_LICENSE_KEY={{ secret_pocket_id_maxmind_api }}
      - ENCRYPTION_KEY={{ secret_pocket_id_encryption_key }}
      - PUID=1000
      - PGID=1000
      - ALLOW_OWN_ACCOUNT_EDIT=true
      - EMAILS_VERIFIED=true
      - EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED=true
      - SMTP_HOST={{ secret_snapraid_smtp_host }}
      - SMTP_PORT=587
      - SMTP_FROM=pocketid@{{ secret_personal_url }}
      - SMTP_USER={{ secret_snapraid_email_address }}
      - SMTP_PASSWORD={{ secret_snapraid_email_pass }}
      - SMTP_TLS=starttls
    ports:
      - 1411:1411
    volumes:
      - "{{ appdata_path }}/pocketid/data:/app/data"
  adguard-sync:
    image: ghcr.io/linuxserver/adguardhome-sync:0.7.8
    container_name: adguard-sync
    volumes:
      - "{{ appdata_path }}/adguardsync/config:/config"
    ports:
      - 8080:8080
    environment:
      - UID={{ main_uid }}
      - GID={{ main_gid }}
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ ntp_timezone }}
    restart: unless-stopped