services:
  adguard:
    image: adguard/adguardhome:v0.107.57
    container_name: adguard
    cap_add:
      - NET_ADMIN
    volumes:
      - "{{ appdata_path }}/adguard/conf:/opt/adguardhome/conf"
      - "{{ appdata_path }}adguard/work:/opt/adguardhome/work"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 81:80/tcp
      - 444:443/tcp
      - 3000:3000/tcp
    restart: always
  crowdsec:
    image: ghcr.io/crowdsecurity/crowdsec:v1.6.5
    container_name: crowdsec
    volumes:
      - "{{ appdata_path }}/crowdsec/data/acquis.yaml:/etc/crowdsec/acquis.yaml"
      - /var/log/auth.log:/var/log/ssh/auth.log:ro
      - "{{ appdata_path }}/crowdsec/db:/var/lib/crowdsec/data/"
    environment:
      - COLLECTIONS=crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/sshd
      - GID=1000
      - DISABLE_LOCAL_API=true
      - AGENT_USERNAME={{ hostname }}
      - AGENT_PASSWORD={{ secret_crowdsec_honor_pw }}
      - LOCAL_API_URL=http://{{ secret_ambition_ip }}:8080
    restart: unless-stopped
  portainer_agent:
    image: portainer/agent:2.26.1
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    environment:
      - AGENT_SECRET={{ secret_portainer_key }}
    restart: always
  adguard-sync:
    image: ghcr.io/linuxserver/adguardhome-sync:0.6.17
    container_name: adguard-sync
    volumes:
      - "{{ appdata_path }}/adguardsync/config:/config"
    ports:
      - 8080:8080
    environment:
      - UID={{ main_uid }}
      - GID={{ main_gid }}
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ ntp_timezone }}
    restart: always