services:
  signal-api:
    image: bbernhard/signal-cli-rest-api:0.98
    container_name: signal-api
    volumes:
      - "{{ appdata_path }}/signal-api:/home/.local/share/signal-cli"
    ports:
      - 8080:8080
    environment:
      - MODE=native
    networks:
      - signal-api-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  signal-api-net:
