services:
  diun:
    image: ghcr.io/crazy-max/diun:4.31.0
    container_name: diun
    volumes:
      - "{{ appdata_path }}/diun/data:/data"
      - "{{ appdata_path }}/diun/config.yml:/diun.yml:ro"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - UID={{ main_uid }}
      - GID={{ main_gid }}
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ ntp_timezone }}
      - LOG_LEVEL=info
      - LOG_JSON=false
    hostname: cultivation
    networks:
      - diun-net
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

networks:
  diun-net:
