---
- name: SSH Keys - Add Phone SSH Key
  authorized_key:
    user: "{{ main_username }}"
    state: present
    key: "{{ secret_pixel_ssh }}"

- name: SSH Keys - Add Work SSH Key
  authorized_key:
    user: "{{ main_username }}"
    state: present
    key: "{{ secret_work_ssh }}"