---
- name: create config directories
  file:
    path: "/home/{{ main_username }}/{{ item }}"
    state: directory
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
  loop:
    - docker
    - docker/diun
    - docker/adguard

### Docker
- name: Add docker deamon file
  copy:
    src: docker-daemon.sjon
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
- name: Restart docker
  service:
    name: docker
    state: restarted

#### DIUN
- name: Copy DIUN Config Template
  template:
    src: diun_config.yml.j2
    dest: /home/{{ main_username }}/docker/diun/config.yml
    owner: "{{ main_username }}"
    group: "{{ main_username }}"

- name: Stop resolved
  service:
    name: systemd-resolved
    enabled: no
    state: stopped
