---
- name: Bash Alias | Add general aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    owner: "{{ bash_user }}"
    group: "{{ bash_user }}"
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  loop: "{{ bash_aliases }}"
  when: bash_aliases is defined

- name: Bash Alias | Add docker aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    owner: "{{ bash_user }}"
    group: "{{ bash_user }}"
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  loop: "{{ bash_docker_aliases }}"
  when: bash_docker != false

- name: Bash Alias | Add systemctl aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    owner: "{{ bash_user }}"
    group: "{{ bash_user }}"
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  loop: "{{ bash_systemctl_aliases }}"
  when: bash_systemctl != false

- name: Bash Alias | Add apt aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    owner: "{{ bash_user }}"
    group: "{{ bash_user }}"
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  loop: "{{ bash_apt_aliases }}"
  when: bash_apt != false

- name: Bash Alias | Add git aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    owner: "{{ bash_user }}"
    group: "{{ bash_user }}"
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  loop: "{{ bash_git_aliases }}"
  when: bash_git != false

- name: Bash Alias | Add autorestic aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    owner: "{{ bash_user }}"
    group: "{{ bash_user }}"
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  loop: "{{ bash_autorestic_aliases }}"
  when: bash_autorestic != false

- name: Bash Alias | Add pacman aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    owner: "{{ bash_user }}"
    group: "{{ bash_user }}"
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  loop: "{{ bash_pacman_aliases }}"
  when: bash_pacman != false

- name: Bash Alias | Add yay aliases
  lineinfile:
    dest: "{{ bash_aliases_path }}"
    create: yes
    owner: "{{ bash_user }}"
    group: "{{ bash_user }}"
    mode: 0644
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
  loop: "{{ bash_yay_aliases }}"
  when: bash_yay != false