---
- name: Install Ansible via Pip
  pip:
    name: ansible

- name: Clone Ansible GitHub Repo
  git:
    repo: git@github.com:FuzzyMistborn/infra.git
    dest: /home/{{ main_username }}/infra
    accept_hostkey: true
    key_file: /home/{{main_username}}/.ssh/github

- name: Add Linode SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/linode
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_linode_ssh }}"

- name: Add Gitea SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/gitea
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_gitea_ssh }}"

- name: Add ansible SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/ansible_user
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_ansible_key }}"

- name: Add ssh config
  copy:
    dest: /home/{{ main_username }}/.ssh/config
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0664
    content: |
      Host github.com
        IdentityFile ~/.ssh/github
      Host gitea
        HostName {{ secret_linode_ip }}
        Port {{ secret_gitea_port }}
        IdentityFile ~/.ssh/gitea
      Host linode
        HostName {{ secret_linode_ip }}
        IdentityFile ~/.ssh/linode

- name: Create update script
  copy:
    dest: /home/{{ main_username }}/update.sh
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
    content: |
      #!/bin/bash
      curl -fsS -m 10 --retry 5 -o /dev/null {{secret_hc_ansible_update}}/start
      cd /home/{{main_username}}/infra
      /usr/local/bin/ansible-playbook update.yml --vault-password-file .vault-password
      curl -fsS -m 10 --retry 5 -o /dev/null {{secret_hc_ansible_update}}/$1

#### Cronjobs
- name: "Main User Cronjobs"
  cron:
    user: "{{ main_username }}"
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
    weekday: "{{ item.weekday }}"
    day: "{{ item.day }}"
    state: present
  with_items:
    - { job: "/home/{{ main_username }}/update.sh", name: "Ansible Update", hour: "19", minute: "30", weekday: "3", day: "*" }
