---
- name: Install Ansible via Pip
  pip:
    name:
      - ansible
      - yamllint

- name: Add Code-Server SSH Key
  authorized_key:
    user: "{{ main_username }}"
    state: present
    key: "{{ secret_main_user_code_server_ssh }}"

- name: Clone Ansible GitHub Repo
  git:
    repo: git@github.com:FuzzyMistborn/infra.git
    dest: /home/{{ main_username }}/infra
    accept_hostkey: true
    key_file: /home/{{main_username}}/.ssh/github

- name: Add Linode SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/linode
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_linode_ssh }}"

- name: Add Gitea SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/gitea
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_gitea_ssh }}"

- name: Add ansible SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/ansible_user
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_ansible_key }}"

- name: Add ssh config
  copy:
    dest: /home/{{ main_username }}/.ssh/config
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0664
    content: |
      Host github.com
        IdentityFile ~/.ssh/github
      Host gitea
        HostName {{ secret_linode_ip }}
        Port {{ secret_gitea_port }}
        IdentityFile ~/.ssh/gitea
      Host linode
        HostName {{ secret_linode_ip }}
        IdentityFile ~/.ssh/linode

- name: Create update script
  copy:
    dest: /home/{{ main_username }}/update.sh
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
    content: |
      #!/bin/bash
      cd /home/{{main_username}}/infra
      /usr/local/bin/ansible-playbook update.yml --vault-password-file .vault-password
      /usr/local/bin/ansible-playbook update.yml --vault-password-file .vault-password --tags "install"

#### Bash Alias

- name: Setup bash aliases
  lineinfile:
    dest: "/etc/bash_aliases"
    create: yes
    group: root
    line: "alias {{ item.alias }}='{{ item.command }}'"
    mode: 0644
    owner: root
    regexp: "^alias {{ item.alias }}="
  with_items:
    - {alias: "gitcheck", command: "/bin/bash /home/{{main_username}}/infra/git-vault-check.sh"}

- name: Source aliases file
  lineinfile:
    dest: /etc/bash.bashrc
    line: 'source /etc/bash_aliases'
    state: present
