---
- name: Add Code-Server SSH Key
  authorized_key:
    user: "{{ main_username }}"
    state: present
    key: "{{ secret_main_user_code_server_ssh }}"

- name: Clone Ansible GitHub Repo
  git:
    repo: git@github.com:FuzzyMistborn/infra.git
    dest: /home/{{ main_username }}/infra
    accept_hostkey: true
    key_file: /home/{{ main_username }}/.ssh/github

- name: Add Ambition SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/ambition
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_ambition_ssh }}"

- name: Add Gitea SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/gitea
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_gitea_ssh }}"

- name: Add ansible SSH Key
  copy:
    dest: /home/{{ main_username }}/.ssh/ansible_user
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0600
    content: "{{ secret_ansible_key }}"

- name: Add ssh config
  copy:
    dest: /home/{{ main_username }}/.ssh/config
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0664
    content: |
      Host github.com
        IdentityFile ~/.ssh/github
      Host git.fuzzymistborn.com
        user git
        HostName remote.fuzzymistborn.com
        Port 222
        IdentityFile ~/.ssh/gitea
      Host ambition
        HostName {{ secret_ambition_ip }}
        IdentityFile ~/.ssh/ambition

- name: Copy update template script
  template:
    src: "{{ item.src }}"
    dest: /home/{{ main_username }}/{{ item.dest }}
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
  with_items:
    - {src: 'update.sh.j2', dest: 'update.sh'}

- name: Create update script
  copy:
    dest: /home/{{ main_username }}/update.sh
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: +x
    content: |
      #!/bin/bash
      cd /home/{{ main_username }}/infra
      /usr/local/bin/ansible-playbook update.yml
      /usr/local/bin/ansible-playbook update.yml --tags "install"

- name: Set BW CLI version
  shell: "bw --version"
  changed_when: false
  register: bw_ver

- name: Set BW CLI Config
  copy:
    dest: "/home/{{ main_username }}/.config/Bitwarden CLI/data.json"
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    mode: 0644
    content: |
      {
        "installedVersion": "{{ bw_ver.stdout }}",
        "environmentUrls": {
          "base": "{{ secret_bitwarden_url }}",
          "api": null,
          "identity": null,
          "webVault": null,
          "icons": null,
          "notifications": null,
          "events": null,
          "keyConnector": null
        }
      }
