name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 5'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v27.14.0
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
