---

- name: get latest release
  uri:
    url: https://api.github.com/repos/bdd/runitor/releases/latest
    return_content: true
  register: release_latest
  when: runitor_ver is undefined

- name: set version if not already
  set_fact: runitor_ver="{{ release_latest.json.tag_name }}"
  when: runitor_ver is undefined

- name: download release
  get_url:
    url: https://github.com/bdd/runitor/releases/download/{{runitor_ver}}/runitor-{{runitor_ver}}-linux-amd64
    dest: /usr/local/bin
    force: yes
    owner: "{{main_username}}"
    group: "{{main_username}}"
    mode: +x

- name: populate /etc/environment
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^HC_API_URL="
    line: "HC_API_URL={{secret_hc_ping_url}}"